"""Insult no afirma su número de versión (issue #58).

La versión de deploy se estampa en `persona_gateway/delivery.py` DESPUÉS de
que el modelo generó el texto: nada la inyecta al contexto del turno, así que
la persona no puede saberla. Cuando se la preguntaban, la confabulaba — el
2026-09-07 dijo dos veces "v4.32.80" (un deploy real de agosto que vivió
semanas en #general) mientras el tag estampado decía ᵛ⁴·³⁸·⁸ y ᵛ⁴·³⁸·¹⁰.

QUÉ PRUEBA ESTE ARCHIVO — y qué NO. No se puede testear lo que el modelo va a
contestar. Lo que sí se puede testear es que el ADN conserve la regla que
produce ese comportamiento, y que viva donde no se la lleve un script.

  1. la regla existe: el ADN dice que NO sabe su versión y a dónde mandar a
     quien pregunte;
  2. la regla vive FUERA del bloque `CAPABILITIES:START/END`. Ese bloque lo
     regenera `scripts/sync_capabilities.py` desde el código en cada commit:
     una línea escrita ahí dentro se borra sola y nadie se entera. Ya pasó una
     vez con TTS, web search, transcripción, recordatorios y deep memory.
"""

from pathlib import Path

import pytest

DNA = Path(__file__).resolve().parents[2] / "shared" / "personas" / "insult.md"
START_MARKER = "<!-- CAPABILITIES:START -->"
END_MARKER = "<!-- CAPABILITIES:END -->"


@pytest.fixture(scope="module")
def dna() -> str:
    text = DNA.read_text(encoding="utf-8")
    assert text.strip(), "el ADN de Insult está vacío"
    return text


def test_dna_says_insult_does_not_know_its_own_version(dna: str) -> None:
    """La regla está escrita, con su razón y con su salida."""
    assert "You do NOT know your own deploy version." in dna
    assert "any number you'd say is invented" in dna
    assert "stamped automatically at the end of your messages" in dna


def test_the_rule_lives_outside_the_autogenerated_block(dna: str) -> None:
    """Dentro de CAPABILITIES:START/END el script la borraría en silencio."""
    rule_at = dna.index("You do NOT know your own deploy version.")
    block = range(dna.index(START_MARKER), dna.index(END_MARKER))
    assert rule_at not in block, (
        "la regla quedó dentro del bloque autogenerado: "
        "scripts/sync_capabilities.py la va a borrar en el próximo commit"
    )
