use data_encoding::BASE32_NOPAD;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};

use super::types::{
    DecodedLicense, LicenseError, LicensePayload, LicenseStatus, LicenseValidationResult,
};

/// Embedded public key for license verification (base64-encoded PEM)
/// Generated by: fi license export-pubkey --format=base64
const LICENSE_PUBLIC_KEY_B64: &str = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQWxDNmI5RmNTNUN2TDJRWlVZdmtpNWZsc0xLYjBRU0xha08rbTZpQ0puS0U9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=";

/// License key prefix
const LICENSE_PREFIX: &str = "AURITY";

/// Load the embedded public key
fn load_public_key() -> Result<VerifyingKey, LicenseError> {
    use base64::Engine;

    let pem_bytes = base64::engine::general_purpose::STANDARD
        .decode(LICENSE_PUBLIC_KEY_B64)
        .map_err(|e| LicenseError::InvalidFormat(format!("Failed to decode public key base64: {}", e)))?;

    let pem_str =
        String::from_utf8(pem_bytes).map_err(|e| LicenseError::InvalidFormat(format!("Invalid PEM encoding: {}", e)))?;

    let lines: Vec<&str> = pem_str.lines().collect();
    let key_data: String = lines
        .iter()
        .filter(|line| !line.starts_with("-----"))
        .copied()
        .collect();

    let der_bytes = base64::engine::general_purpose::STANDARD
        .decode(&key_data)
        .map_err(|e| LicenseError::InvalidFormat(format!("Failed to decode PEM content: {}", e)))?;

    // DER format for Ed25519 public key:
    // 30 2A (SEQUENCE, 42 bytes)
    //   30 05 (SEQUENCE, 5 bytes) - Algorithm identifier
    //     06 03 2B 65 70 (OID 1.3.101.112 = Ed25519)
    //   03 21 00 (BIT STRING, 33 bytes, 0 unused bits)
    //     [32 bytes of public key]
    if der_bytes.len() < 44 {
        return Err(LicenseError::InvalidFormat("Invalid DER encoding: too short".into()));
    }

    let key_bytes = &der_bytes[der_bytes.len() - 32..];

    VerifyingKey::from_bytes(key_bytes.try_into().map_err(|_| LicenseError::InvalidFormat("Invalid key length".into()))?)
        .map_err(|e| LicenseError::InvalidFormat(format!("Invalid Ed25519 public key: {}", e)))
}

/// Decode a license key into payload, original bytes, and signature
pub fn decode_license_key(license_key: &str) -> Result<DecodedLicense, LicenseError> {
    let key = license_key.to_uppercase().replace('-', "");

    if !key.starts_with(LICENSE_PREFIX) {
        return Err(LicenseError::InvalidFormat(format!(
            "Invalid license key: must start with {}",
            LICENSE_PREFIX
        )));
    }

    let encoded = &key[LICENSE_PREFIX.len()..];

    let combined = BASE32_NOPAD
        .decode(encoded.as_bytes())
        .map_err(|e| LicenseError::InvalidFormat(format!("Invalid license key encoding: {}", e)))?;

    if combined.len() < 4 {
        return Err(LicenseError::InvalidFormat("Invalid license key: too short".into()));
    }

    let payload_len =
        u32::from_be_bytes([combined[0], combined[1], combined[2], combined[3]]) as usize;

    if combined.len() < 4 + payload_len + 64 {
        return Err(LicenseError::InvalidFormat("Invalid license key: incomplete data".into()));
    }

    let payload_bytes = combined[4..4 + payload_len].to_vec();
    let signature_bytes = combined[4 + payload_len..4 + payload_len + 64].to_vec();

    let payload_str = String::from_utf8(payload_bytes.clone())
        .map_err(|e| LicenseError::InvalidFormat(format!("Invalid payload encoding: {}", e)))?;

    let payload: LicensePayload = serde_json::from_str(&payload_str)
        .map_err(|e| LicenseError::InvalidFormat(format!("Invalid license payload: {}", e)))?;

    Ok(DecodedLicense {
        payload,
        payload_bytes,
        signature_bytes,
    })
}

/// Verify a license key's signature
pub fn verify_license_signature(license_key: &str) -> Result<LicensePayload, LicenseError> {
    let decoded = decode_license_key(license_key)?;

    let public_key = load_public_key()?;

    let sig_array: [u8; 64] = decoded
        .signature_bytes
        .as_slice()
        .try_into()
        .map_err(|_| LicenseError::InvalidSignature("Invalid signature length: expected 64 bytes".into()))?;
    let signature = Signature::from_bytes(&sig_array);

    // Verify using the ORIGINAL payload bytes (not re-serialized)
    public_key
        .verify(&decoded.payload_bytes, &signature)
        .map_err(|_| LicenseError::InvalidSignature("Invalid license signature".into()))?;

    Ok(decoded.payload)
}

/// Validate a license key completely
pub fn validate_license(license_key: &str) -> LicenseValidationResult {
    let payload = match verify_license_signature(license_key) {
        Ok(p) => p,
        Err(e) => {
            let status = match &e {
                LicenseError::InvalidFormat(_) => LicenseStatus::InvalidFormat,
                LicenseError::InvalidSignature(_) => LicenseStatus::InvalidSignature,
                _ => LicenseStatus::InvalidFormat,
            };
            return LicenseValidationResult {
                status: status.as_str().to_string(),
                is_valid: false,
                message: e.to_string(),
                days_remaining: None,
                payload: None,
            };
        }
    };

    if payload.is_expired() {
        return LicenseValidationResult {
            status: LicenseStatus::Expired.as_str().to_string(),
            is_valid: false,
            message: "License has expired".to_string(),
            days_remaining: payload.days_remaining(),
            payload: Some(payload),
        };
    }

    LicenseValidationResult {
        status: LicenseStatus::Valid.as_str().to_string(),
        is_valid: true,
        message: "License is valid".to_string(),
        days_remaining: payload.days_remaining(),
        payload: Some(payload),
    }
}
