version: "3.8"

# Free Intelligence - ASR Worker (faster-whisper)
# Optimized for CPU (DS923+)
#
# Usage:
#   docker compose -f docker-compose.asr.yml up -d
#   # Place audio files in /volume1/fi/ready/
#   # Results in /volume1/fi/asr/json/

services:
  fi-asr-worker:
    image: python:3.11-slim
    container_name: fi-asr-worker
    restart: unless-stopped

    environment:
      # I/O directories
      - IN_DIR=/data/ready
      - OUT_DIR=/data/asr/json
      - LOG_DIR=/data/asr/logs

      # Whisper model configuration
      - MODEL=small              # tiny|base|small|medium|large-v3
      - LANG=es                  # Language code
      - COMPUTE=int8             # int8|float16|float32 (int8 fastest on CPU)

      # Performance tuning
      - VAD=true                 # Voice Activity Detection (cuts silence)
      - BEAM=1                   # Beam size (1=fastest, 5=better quality)
      - VAD_MIN_SILENCE_MS=300   # Min silence to split (ms)

      # Worker settings
      - POLL_INTERVAL=2          # Seconds between dir scans
      - MAX_WORKERS=2            # Parallel files (adjust for CPU)

    volumes:
      - /volume1/fi:/data
      - ./scripts/asr_worker.py:/app/worker.py:ro

    command: >
      bash -lc "
      apt-get update && apt-get install -y --no-install-recommends curl ffmpeg &&
      pip install --no-cache-dir faster-whisper==1.0.* &&
      python /app/worker.py"

    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/worker.pid"]
      interval: 30s
      timeout: 5s
      retries: 3

    deploy:
      resources:
        limits:
          cpus: '3.0'           # Reserve CPU for transcription
          memory: 6G
        reservations:
          cpus: '2.0'
          memory: 4G

    networks:
      - fi-network

networks:
  fi-network:
    driver: bridge
