/**
 * ModelBadge Component
 *
 * Displays "Powered by [LLM Model]" badge for assistant messages
 * Shows the specific LLM model that generated the response
 *
 * Created: 2025-12-22
 * Author: Bernard Uriza Orozco
 */

import { Sparkles } from 'lucide-react';
import { getVoiceDisplayName } from '@/lib/voiceAliases';

interface ModelBadgeProps {
  model: string;
  className?: string;
  voice?: string | null;
}

/**
 * Format model name for display
 * Examples:
 *   "qwen3:1.7b" → "Qwen3 1.7B"
 *   "claude-sonnet-4" → "Claude Sonnet 4"
 *   "gpt-4" → "GPT-4"
 */
function formatModelName(model: string): string {
  // Handle Ollama-style models (e.g., "qwen3:1.7b")
  if (model.includes(':')) {
    const [name, version] = model.split(':');
    const formattedName = name.charAt(0).toUpperCase() + name.slice(1);
    const formattedVersion = version.toUpperCase().replace('b', 'B');
    return `${formattedName} ${formattedVersion}`;
  }

  // Handle hyphenated models (e.g., "claude-sonnet-4")
  if (model.includes('-')) {
    return model
      .split('-')
      .map(part => part.charAt(0).toUpperCase() + part.slice(1))
      .join(' ');
  }

  // Default: capitalize first letter
  return model.charAt(0).toUpperCase() + model.slice(1);
}


export function ModelBadge({ model, className = '', voice = null }: ModelBadgeProps) {
  const displayName = formatModelName(model);
  const showVoice = typeof voice === 'string' && voice.length > 0;
  const voiceLabel = showVoice ? getVoiceDisplayName(voice as string) ?? '' : '';

  return (
    <div
      className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-slate-800/50 border border-slate-700/50 fi-text-xs ${className}`}
      title={`Generated by ${displayName}`}
    >
      <Sparkles className="w-3 h-3 fi-text-success/80" aria-hidden="true" />
      <span className="font-medium flex items-center gap-2">
        <span>
          Powered by <span className="fi-text-success/90">{displayName}</span>
        </span>
        {showVoice && (
          <span className="fi-text-xs/80 px-2 py-0.5 rounded-full bg-slate-700/30 border border-slate-700/30">
            Voice of <span className="text-emerald-300 font-mono">{voiceLabel}</span>
          </span>
        )}
      </span>
    </div>
  );
}
