"""Vector embedding and semantic search for user facts.

Post-PG migration: uses pgvector inside Postgres for vector storage and
ANN search. Embedding generation stays local via sentence-transformers
(`all-MiniLM-L6-v2`, 384d, normalized) — no network calls.

Why FTS5 is gone:
- SQLite FTS5 was the keyword half of the RRF hybrid. Postgres ships
  `tsvector` + `to_tsquery` but the bot already has a cheap LIKE search
  in `MessagesRepository.search` and `FactsRepository.search_facts_semantic`
  falls back to `get_facts()` on miss. Adding tsvector here would mean a
  second migration + GIN index + tokenizer config — not worth blocking
  the PG cutover for a feature that the messages-LIKE path already covers.
- If semantic-only search degrades in practice, the follow-up is to add
  a `facts_tsv` column with a GIN index and re-introduce RRF using
  `ts_rank_cd` for the keyword side. Schema is reserved for that move.
"""

from __future__ import annotations

import threading
from typing import TYPE_CHECKING

import structlog

if TYPE_CHECKING:
    import asyncpg

log = structlog.get_logger()

EMBEDDING_DIM = 384
MODEL_NAME = "all-MiniLM-L6-v2"


class EmbeddingModel:
    """Lazy-loaded sentence-transformers model for generating embeddings.

    Thread-safe: model loading is protected by a lock so concurrent
    callers don't race to initialize the model.
    """

    def __init__(self) -> None:
        self._model = None
        self._lock = threading.Lock()

    def _ensure_model(self) -> None:
        """Load the model on first use (lazy initialization)."""
        if self._model is not None:
            return
        with self._lock:
            if self._model is not None:
                return
            from sentence_transformers import SentenceTransformer

            self._model = SentenceTransformer(MODEL_NAME)
            log.info("embedding_model_loaded", model=MODEL_NAME, dim=EMBEDDING_DIM)

    def embed(self, text: str) -> list[float]:
        """Generate a 384-dimensional embedding for a single text."""
        self._ensure_model()
        vector = self._model.encode(text, normalize_embeddings=True)
        return vector.tolist()

    def embed_batch(self, texts: list[str]) -> list[list[float]]:
        """Generate embeddings for multiple texts at once."""
        if not texts:
            return []
        self._ensure_model()
        vectors = self._model.encode(texts, normalize_embeddings=True)
        return [v.tolist() for v in vectors]


# Module-level singleton (lazy — no work done until first .embed() call)
_embedding_model: EmbeddingModel | None = None


def get_embedding_model() -> EmbeddingModel:
    """Get or create the singleton EmbeddingModel instance."""
    global _embedding_model
    if _embedding_model is None:
        _embedding_model = EmbeddingModel()
    return _embedding_model


async def upsert_fact_vectors(pool: asyncpg.Pool, user_id: str, facts: list[dict]) -> None:
    """Embed facts and upsert into `fact_embeddings`.

    Called after `FactsRepository.save_facts` finishes its primary INSERT.
    `facts` is a list of dicts with `id`, `fact`, `category` keys — but we
    re-read from the DB here because `save_facts` doesn't expose the new
    autogenerated ids back to the caller.
    """
    if not facts:
        return

    model = get_embedding_model()

    async with pool.acquire() as conn:
        # Pull all live facts for this user (post-INSERT) so we have ids.
        rows = await conn.fetch(
            "SELECT id, fact FROM principal_facts WHERE principal_id = $1 AND deleted_at IS NULL ORDER BY id",
            user_id,
        )
        if not rows:
            return

        fact_ids = [r["id"] for r in rows]
        fact_texts = [r["fact"] for r in rows]
        embeddings = model.embed_batch(fact_texts)

        # Drop any prior embeddings for this user's facts (CASCADE handles it
        # for hard-deletes, but auto-extraction does soft-replace, so the
        # previous run's ids are gone before this call lands).
        await conn.execute(
            "DELETE FROM fact_embeddings WHERE fact_id NOT IN ("
            "SELECT id FROM principal_facts WHERE principal_id = $1 AND deleted_at IS NULL"
            ")",
            user_id,
        )

        import time

        now = time.time()
        await conn.executemany(
            "INSERT INTO fact_embeddings (fact_id, embedding, updated_at) VALUES ($1, $2, $3) "
            "ON CONFLICT (fact_id) DO UPDATE SET "
            "embedding = excluded.embedding, updated_at = excluded.updated_at",
            [(fid, emb, now) for fid, emb in zip(fact_ids, embeddings, strict=False)],
        )

    log.info("fact_vectors_upserted", user_id=user_id, count=len(fact_ids))


async def search_facts_hybrid(
    pool: asyncpg.Pool,
    user_id: str,
    query: str,
    limit: int = 10,
) -> list[dict]:
    """Cosine-similarity search over the user's fact embeddings.

    Returns the top-K facts ordered by ascending vector distance (closest
    first). When the user has no embeddings yet, returns an empty list —
    the caller (`FactsRepository.search_facts_semantic`) falls back to
    plain `get_facts()` in that case.

    Despite the `hybrid` name kept for callsite compatibility, the FTS5
    half is gone (see module docstring). The LIKE search in
    `MessagesRepository.search` continues to provide the keyword path
    via the recent-+-relevant context builder.
    """
    model = get_embedding_model()
    query_embedding = model.embed(query)

    rows = await pool.fetch(
        "SELECT pf.id, pf.fact, pf.category, pf.updated_at, "
        "(fe.embedding <=> $2::vector) AS distance "
        "FROM principal_facts pf JOIN fact_embeddings fe ON fe.fact_id = pf.id "
        "WHERE pf.principal_id = $1 AND pf.deleted_at IS NULL "
        "ORDER BY fe.embedding <=> $2::vector "
        "LIMIT $3",
        user_id,
        query_embedding,
        limit,
    )
    return [
        {
            "id": r["id"],
            "fact": r["fact"],
            "category": r["category"],
            "updated_at": r["updated_at"],
            # Convert cosine distance to a similarity-ish score so callers
            # that previously sorted by `rrf_score DESC` keep their semantics.
            "rrf_score": 1.0 - float(r["distance"]),
        }
        for r in rows
    ]
