/**
 * Downloads Page
 *
 * Displays available Aurity Desktop releases for download.
 * Fetches release information from /releases.json endpoint.
 *
 * NOTE: This page is hidden in desktop mode (you're already running the app!)
 */

'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { AppTemplate } from '@/components/layout/AppTemplate';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/hooks/useAuth';
import {
  Download,
  Apple,
  Monitor,
  Shield,
  Cpu,
  HardDrive,
  RefreshCw,
  CheckCircle,
  ExternalLink,
  CheckCircle2,
  MessageSquare,
} from 'lucide-react';

// Check if running in desktop mode
const isDesktop = () => {
  if (typeof window === 'undefined') return false;
  // Check Tauri
  if ('__TAURI__' in window) return true;
  // Check env var
  if (process.env.NEXT_PUBLIC_DEPLOYMENT_TARGET === 'desktop') return true;
  return false;
};

interface Release {
  version: string;
  date: string;
  platforms: {
    macos?: {
      url: string;
      size: string;
      sha256: string;
    };
    windows?: {
      url: string;
      size: string;
      sha256: string;
    };
    linux?: {
      url: string;
      size: string;
      sha256: string;
    };
  };
  changelog?: string[];
}

const features = [
  {
    icon: Shield,
    title: '100% Offline',
    description: 'Todo el procesamiento de IA ocurre en tu dispositivo. Ningún dato sale de tu computadora.',
  },
  {
    icon: Cpu,
    title: 'LLM Local',
    description: 'Potenciado por Ollama con Qwen3, Llama, o tu modelo preferido.',
  },
  {
    icon: HardDrive,
    title: 'Tus Datos',
    description: 'Expedientes médicos almacenados localmente en ~/.aurity con encriptación completa.',
  },
];

const systemRequirements = {
  macos: {
    os: 'macOS 12.0 (Monterey) o posterior',
    cpu: 'Apple Silicon (M1/M2/M3) o Intel',
    ram: '8 GB mínimo, 16 GB recomendado',
    disk: '10 GB de espacio libre',
  },
  windows: {
    os: 'Windows 10 (64-bit) o Windows 11',
    cpu: 'Procesador x86_64',
    ram: '8 GB mínimo, 16 GB recomendado',
    disk: '10 GB de espacio libre',
  },
  linux: {
    os: 'Ubuntu 22.04 LTS o compatible',
    cpu: 'Procesador x86_64',
    ram: '8 GB mínimo, 16 GB recomendado',
    disk: '10 GB de espacio libre',
  },
};

// Releases are loaded from /releases.json (generated by CI/CD)
interface ReleasesData {
  releases: Release[];
  generatedAt: string;
  source: string;
}

export default function DownloadsPage() {
  const router = useRouter();
  const { isAuthenticated, isLoading: authLoading } = useAuth();
  const [releases, setReleases] = useState<Release[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isDesktopMode, setIsDesktopMode] = useState(false);

  useEffect(() => {
    // Check if running in desktop mode
    if (isDesktop()) {
      setIsDesktopMode(true);
    } else {
      // Fetch latest release from GitHub API
      fetchLatestRelease();
    }
  }, []);

  const fetchLatestRelease = async () => {
    setLoading(true);
    setError(null);

    try {
      // Fetch releases from static JSON (generated by CI/CD)
      const response = await fetch('/releases.json');
      if (!response.ok) {
        throw new Error(`Error al obtener releases: ${response.status}`);
      }

      const data: ReleasesData = await response.json();

      if (data.releases && data.releases.length > 0) {
        setReleases(data.releases);
      } else {
        setError('No hay releases disponibles');
      }
    } catch (err) {
      console.error('Error fetching releases:', err);
      setError('Error al cargar releases. Por favor intenta más tarde.');
    } finally {
      setLoading(false);
    }
  };

  // Show "already installed" message in desktop mode
  if (isDesktopMode) {
    return (
      <AppTemplate backgroundGradient="none">
        <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white dark:from-slate-900 dark:to-slate-800 flex items-center justify-center">
          <div className="text-center p-8 max-w-md">
            <CheckCircle2 className="w-16 h-16 text-green-500 mx-auto mb-4" />
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">
              Ya tienes Aurity Desktop
            </h1>
            <p className="text-slate-600 dark:text-slate-300 mb-6">
              Estás corriendo la aplicación de escritorio.
              No necesitas descargar nada más.
            </p>
            <Button onClick={() => router.push('/chat')}>
              Ir al Chat
            </Button>
          </div>
        </div>
      </AppTemplate>
    );
  }

  const latestRelease = releases[0];

  // For unauthenticated users: show landing page with giant download button
  if (!authLoading && !isAuthenticated) {
    return (
      <AppTemplate backgroundGradient="none">
        <div className="min-h-screen bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900 flex flex-col">
          {/* Hero Section */}
          <div className="flex-1 flex flex-col items-center justify-center px-4 py-8 sm:py-12">
            <div className="text-center max-w-3xl mx-auto w-full">
              <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-4 sm:mb-6">
                Aurity Desktop
              </h1>
              <p className="text-base sm:text-lg md:text-xl lg:text-2xl text-slate-300 mb-6 sm:mb-8 px-2">
                Asistente médico con IA que corre 100% en tu dispositivo.
                <br className="hidden sm:block" />
                <span className="text-emerald-400"> Sin nube. Sin compartir datos. Privacidad total.</span>
              </p>

              {/* Giant Download Button */}
              {loading ? (
                <div className="flex justify-center py-6 sm:py-8">
                  <RefreshCw className="w-6 h-6 sm:w-8 sm:h-8 animate-spin text-emerald-500" />
                </div>
              ) : error ? (
                <div className="flex flex-col items-center py-6 sm:py-8">
                  <p className="text-red-400 mb-4 text-sm sm:text-base">{error}</p>
                  <Button onClick={fetchLatestRelease} variant="outline" className="border-slate-600 text-slate-300">
                    <RefreshCw className="w-4 h-4 mr-2" />
                    Reintentar
                  </Button>
                </div>
              ) : (
                <div className="space-y-3 sm:space-y-4 px-2">
                  <Button
                    size="lg"
                    className="w-full sm:w-auto h-14 sm:h-16 md:h-20 px-6 sm:px-8 md:px-12 text-lg sm:text-xl md:text-2xl bg-emerald-600 hover:bg-emerald-700 text-white shadow-2xl shadow-emerald-500/30"
                    onClick={() => {
                      // Detect OS and download appropriate version
                      const ua = navigator.userAgent.toLowerCase();
                      let downloadUrl = '';
                      if (ua.includes('mac')) {
                        downloadUrl = latestRelease?.platforms.macos?.url || '';
                      } else if (ua.includes('win')) {
                        downloadUrl = latestRelease?.platforms.windows?.url || '';
                      } else if (ua.includes('linux')) {
                        downloadUrl = latestRelease?.platforms.linux?.url || '';
                      }
                      if (downloadUrl && downloadUrl !== '#coming-soon') {
                        window.open(downloadUrl, '_blank');
                      }
                    }}
                  >
                    <Download className="w-5 h-5 sm:w-6 sm:h-6 md:w-8 md:h-8 mr-2 sm:mr-3" />
                    Descargar Gratis
                  </Button>
                  {latestRelease && (
                    <p className="text-slate-400 text-xs sm:text-sm">
                      Versión {latestRelease.version} · macOS, Windows y Linux
                    </p>
                  )}
                </div>
              )}

              {/* CTA to Chat */}
              <div className="mt-8 sm:mt-12 pt-6 sm:pt-8 border-t border-slate-700 px-2">
                <p className="text-slate-400 mb-3 sm:mb-4 text-sm sm:text-base">¿Prefieres la versión en la nube?</p>
                <Button
                  variant="outline"
                  size="lg"
                  className="w-full sm:w-auto border-slate-600 text-slate-300 hover:bg-slate-800"
                  onClick={() => router.push('/chat')}
                >
                  <MessageSquare className="w-4 h-4 sm:w-5 sm:h-5 mr-2" />
                  Ir al Chat Web
                </Button>
              </div>
            </div>
          </div>

          {/* Features */}
          <div className="bg-slate-800/50 py-8 sm:py-12 md:py-16 px-4">
            <div className="max-w-5xl mx-auto">
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6 md:gap-8">
                {features.map((feature) => (
                  <div
                    key={feature.title}
                    className="bg-slate-800 rounded-xl p-4 sm:p-6 border border-slate-700"
                  >
                    <feature.icon className="w-8 h-8 sm:w-10 sm:h-10 text-emerald-400 mb-3 sm:mb-4" />
                    <h3 className="text-base sm:text-lg font-semibold text-white mb-2">
                      {feature.title}
                    </h3>
                    <p className="text-slate-400 text-sm sm:text-base">
                      {feature.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </AppTemplate>
    );
  }

  // For authenticated users: show full downloads page
  return (
    <AppTemplate backgroundGradient="none">
      <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white dark:from-slate-900 dark:to-slate-800">
        {/* Hero Section */}
        <div className="max-w-6xl mx-auto px-4 py-6 sm:py-8 md:py-12">
          <div className="text-center mb-6 sm:mb-8 md:mb-12">
            <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-slate-900 dark:text-white mb-3 sm:mb-4">
              Aurity Desktop
            </h1>
            <p className="text-base sm:text-lg md:text-xl text-slate-600 dark:text-slate-300 max-w-2xl mx-auto px-2">
              Asistente médico con IA que corre 100% en tu dispositivo.
              Sin nube. Sin compartir datos. Privacidad total.
            </p>
          </div>

          {/* Features */}
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6 mb-6 sm:mb-8 md:mb-12">
            {features.map((feature) => (
              <div
                key={feature.title}
                className="bg-white dark:bg-slate-800 rounded-xl p-4 sm:p-6 shadow-sm border border-slate-200 dark:border-slate-700"
              >
                <feature.icon className="w-6 h-6 sm:w-8 sm:h-8 text-blue-600 dark:text-blue-400 mb-3 sm:mb-4" />
                <h3 className="text-base sm:text-lg font-semibold text-slate-900 dark:text-white mb-2">
                  {feature.title}
                </h3>
                <p className="text-sm sm:text-base text-slate-600 dark:text-slate-300">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>

          {/* Download Cards */}
          {loading ? (
            <div className="flex justify-center py-8 sm:py-12">
              <RefreshCw className="w-6 h-6 sm:w-8 sm:h-8 animate-spin text-blue-600" />
            </div>
          ) : error ? (
            <div className="flex flex-col items-center justify-center py-8 sm:py-12">
              <p className="text-red-500 mb-4 text-sm sm:text-base">{error}</p>
              <Button onClick={fetchLatestRelease} variant="outline">
                <RefreshCw className="w-4 h-4 mr-2" />
                Reintentar
              </Button>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 mb-6 sm:mb-8 md:mb-12">
              {/* macOS Download */}
              <div className="bg-white dark:bg-slate-800 rounded-xl p-4 sm:p-6 md:p-8 shadow-lg border border-slate-200 dark:border-slate-700">
                <div className="flex items-center gap-3 sm:gap-4 mb-4 sm:mb-6">
                  <div className="w-12 h-12 sm:w-14 sm:h-14 md:w-16 md:h-16 bg-slate-100 dark:bg-slate-700 rounded-xl sm:rounded-2xl flex items-center justify-center flex-shrink-0">
                    <Apple className="w-7 h-7 sm:w-8 sm:h-8 md:w-10 md:h-10 text-slate-700 dark:text-slate-300" />
                  </div>
                  <div className="min-w-0">
                    <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
                      macOS
                    </h2>
                    <p className="text-slate-500 text-sm sm:text-base truncate">Apple Silicon e Intel</p>
                  </div>
                </div>

                {latestRelease?.platforms.macos ? (
                  <>
                    <Button
                      className="w-full mb-3 sm:mb-4 h-10 sm:h-12 text-base sm:text-lg"
                      onClick={() => {
                        if (latestRelease.platforms.macos?.url !== '#coming-soon') {
                          window.open(latestRelease.platforms.macos?.url, '_blank');
                        }
                      }}
                      disabled={latestRelease.platforms.macos.url === '#coming-soon'}
                    >
                      <Download className="w-4 h-4 sm:w-5 sm:h-5 mr-2" />
                      {latestRelease.platforms.macos.url === '#coming-soon'
                        ? 'Próximamente'
                        : `Descargar v${latestRelease.version}`}
                    </Button>
                    <div className="text-xs sm:text-sm text-slate-500 space-y-1">
                      <p>Tamaño: {latestRelease.platforms.macos.size}</p>
                      <p className="font-mono text-[10px] sm:text-xs truncate">
                        SHA256: {latestRelease.platforms.macos.sha256}
                      </p>
                    </div>
                  </>
                ) : (
                  <p className="text-slate-500 text-sm">Aún no disponible</p>
                )}

                <hr className="my-4 sm:my-6 border-slate-200 dark:border-slate-700" />

                <h3 className="font-semibold text-slate-900 dark:text-white mb-2 sm:mb-3 text-sm sm:text-base">
                  Requisitos del Sistema
                </h3>
                <ul className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 space-y-1.5 sm:space-y-2">
                  {Object.entries(systemRequirements.macos).map(([key, value]) => (
                    <li key={key} className="flex items-start gap-2">
                      <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-green-500 mt-0.5 flex-shrink-0" />
                      <span>{value}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Windows Download */}
              <div className="bg-white dark:bg-slate-800 rounded-xl p-4 sm:p-6 md:p-8 shadow-lg border border-slate-200 dark:border-slate-700">
                <div className="flex items-center gap-3 sm:gap-4 mb-4 sm:mb-6">
                  <div className="w-12 h-12 sm:w-14 sm:h-14 md:w-16 md:h-16 bg-slate-100 dark:bg-slate-700 rounded-xl sm:rounded-2xl flex items-center justify-center flex-shrink-0">
                    <Monitor className="w-7 h-7 sm:w-8 sm:h-8 md:w-10 md:h-10 text-slate-700 dark:text-slate-300" />
                  </div>
                  <div className="min-w-0">
                    <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
                      Windows
                    </h2>
                    <p className="text-slate-500 text-sm sm:text-base truncate">Instalador (x64)</p>
                  </div>
                </div>

                {latestRelease?.platforms.windows ? (
                  <>
                    <Button
                      className="w-full mb-3 sm:mb-4 h-10 sm:h-12 text-base sm:text-lg"
                      onClick={() => {
                        if (latestRelease.platforms.windows?.url !== '#coming-soon') {
                          window.open(latestRelease.platforms.windows?.url, '_blank');
                        }
                      }}
                      disabled={latestRelease.platforms.windows.url === '#coming-soon'}
                    >
                      <Download className="w-4 h-4 sm:w-5 sm:h-5 mr-2" />
                      {latestRelease.platforms.windows.url === '#coming-soon'
                        ? 'Próximamente'
                        : `Descargar v${latestRelease.version}`}
                    </Button>
                    <div className="text-xs sm:text-sm text-slate-500 space-y-1">
                      <p>Tamaño: {latestRelease.platforms.windows.size}</p>
                      <p className="font-mono text-[10px] sm:text-xs truncate">
                        SHA256: {latestRelease.platforms.windows.sha256}
                      </p>
                    </div>
                  </>
                ) : (
                  <p className="text-slate-500 text-sm">Aún no disponible</p>
                )}

                <hr className="my-4 sm:my-6 border-slate-200 dark:border-slate-700" />

                <h3 className="font-semibold text-slate-900 dark:text-white mb-2 sm:mb-3 text-sm sm:text-base">
                  Requisitos del Sistema
                </h3>
                <ul className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 space-y-1.5 sm:space-y-2">
                  {Object.entries(systemRequirements.windows).map(([key, value]) => (
                    <li key={key} className="flex items-start gap-2">
                      <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-green-500 mt-0.5 flex-shrink-0" />
                      <span>{value}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Linux Download */}
              <div className="bg-white dark:bg-slate-800 rounded-xl p-4 sm:p-6 md:p-8 shadow-lg border border-slate-200 dark:border-slate-700 sm:col-span-2 lg:col-span-1">
                <div className="flex items-center gap-3 sm:gap-4 mb-4 sm:mb-6">
                  <div className="w-12 h-12 sm:w-14 sm:h-14 md:w-16 md:h-16 bg-slate-100 dark:bg-slate-700 rounded-xl sm:rounded-2xl flex items-center justify-center flex-shrink-0">
                    <Monitor className="w-7 h-7 sm:w-8 sm:h-8 md:w-10 md:h-10 text-slate-700 dark:text-slate-300" />
                  </div>
                  <div className="min-w-0">
                    <h2 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">
                      Linux
                    </h2>
                    <p className="text-slate-500 text-sm sm:text-base truncate">AppImage (x86_64)</p>
                  </div>
                </div>

                {latestRelease?.platforms.linux ? (
                  <>
                    <Button
                      className="w-full mb-3 sm:mb-4 h-10 sm:h-12 text-base sm:text-lg"
                      onClick={() => {
                        if (latestRelease.platforms.linux?.url !== '#coming-soon') {
                          window.open(latestRelease.platforms.linux?.url, '_blank');
                        }
                      }}
                      disabled={latestRelease.platforms.linux.url === '#coming-soon'}
                    >
                      <Download className="w-4 h-4 sm:w-5 sm:h-5 mr-2" />
                      {latestRelease.platforms.linux.url === '#coming-soon'
                        ? 'Próximamente'
                        : `Descargar v${latestRelease.version}`}
                    </Button>
                    <div className="text-xs sm:text-sm text-slate-500 space-y-1">
                      <p>Tamaño: {latestRelease.platforms.linux.size}</p>
                      <p className="font-mono text-[10px] sm:text-xs truncate">
                        SHA256: {latestRelease.platforms.linux.sha256}
                      </p>
                    </div>
                  </>
                ) : (
                  <p className="text-slate-500 text-sm">Aún no disponible</p>
                )}

                <hr className="my-4 sm:my-6 border-slate-200 dark:border-slate-700" />

                <h3 className="font-semibold text-slate-900 dark:text-white mb-2 sm:mb-3 text-sm sm:text-base">
                  Requisitos del Sistema
                </h3>
                <ul className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 space-y-1.5 sm:space-y-2">
                  {Object.entries(systemRequirements.linux).map(([key, value]) => (
                    <li key={key} className="flex items-start gap-2">
                      <CheckCircle className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-green-500 mt-0.5 flex-shrink-0" />
                      <span>{value}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}

          {/* Changelog */}
          {latestRelease?.changelog && (
            <div className="bg-white dark:bg-slate-800 rounded-xl p-4 sm:p-6 md:p-8 shadow-sm border border-slate-200 dark:border-slate-700 mb-6 sm:mb-8 md:mb-12">
              <h2 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white mb-3 sm:mb-4">
                Novedades en v{latestRelease.version}
              </h2>
              <ul className="space-y-1.5 sm:space-y-2">
                {latestRelease.changelog.map((item, index) => (
                  <li
                    key={index}
                    className="flex items-start gap-2 text-sm sm:text-base text-slate-600 dark:text-slate-300"
                  >
                    <CheckCircle className="w-4 h-4 sm:w-5 sm:h-5 text-green-500 mt-0.5 flex-shrink-0" />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Installation Instructions */}
          <div className="bg-slate-100 dark:bg-slate-800/50 rounded-xl p-4 sm:p-6 md:p-8">
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white mb-4">
              Instalación
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6">
              <div>
                <h3 className="font-semibold text-slate-900 dark:text-white mb-2 sm:mb-3 flex items-center gap-2 text-sm sm:text-base">
                  <Apple className="w-4 h-4 sm:w-5 sm:h-5" /> macOS
                </h3>
                <ol className="text-slate-600 dark:text-slate-300 space-y-1.5 sm:space-y-2 list-decimal list-inside text-xs sm:text-sm">
                  <li>Descarga el archivo .dmg</li>
                  <li>Haz doble clic para abrir</li>
                  <li>Arrastra Aurity a Aplicaciones</li>
                  <li>Primera vez: Clic derecho → Abrir</li>
                </ol>
              </div>
              <div>
                <h3 className="font-semibold text-slate-900 dark:text-white mb-2 sm:mb-3 flex items-center gap-2 text-sm sm:text-base">
                  <Monitor className="w-4 h-4 sm:w-5 sm:h-5" /> Windows
                </h3>
                <ol className="text-slate-600 dark:text-slate-300 space-y-1.5 sm:space-y-2 list-decimal list-inside text-xs sm:text-sm">
                  <li>Descarga el instalador .exe</li>
                  <li>Ejecuta el instalador</li>
                  <li>Clic en &quot;Más información&quot; → &quot;Ejecutar&quot;</li>
                  <li>Sigue el asistente</li>
                </ol>
              </div>
              <div className="sm:col-span-2 md:col-span-1">
                <h3 className="font-semibold text-slate-900 dark:text-white mb-2 sm:mb-3 flex items-center gap-2 text-sm sm:text-base">
                  <Monitor className="w-4 h-4 sm:w-5 sm:h-5" /> Linux
                </h3>
                <ol className="text-slate-600 dark:text-slate-300 space-y-1.5 sm:space-y-2 list-decimal list-inside text-xs sm:text-sm">
                  <li>Descarga el archivo .AppImage</li>
                  <li className="break-all">Hazlo ejecutable: <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded text-[10px] sm:text-xs">chmod +x Aurity*.AppImage</code></li>
                  <li className="break-all">Ejecuta: <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded text-[10px] sm:text-xs">./Aurity*.AppImage</code></li>
                </ol>
              </div>
            </div>

            <div className="mt-4 sm:mt-6 p-3 sm:p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
              <p className="text-blue-800 dark:text-blue-200 text-xs sm:text-sm">
                <strong>Nota:</strong> Aurity Desktop requiere{' '}
                <a
                  href="https://ollama.ai"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline inline-flex items-center gap-1"
                >
                  Ollama <ExternalLink className="w-3 h-3" />
                </a>{' '}
                para IA local. Instala Ollama primero, luego ejecuta{' '}
                <code className="bg-blue-100 dark:bg-blue-800 px-1 rounded text-[10px] sm:text-xs">ollama pull qwen3:8b</code>{' '}
                para descargar un modelo.
              </p>
            </div>
          </div>
        </div>
      </div>
    </AppTemplate>
  );
}
