/**
 * Downloads Page - Landing Page Optimizada
 *
 * Diseño basado en mejores prácticas 2025-2026 de SaaS landing pages:
 * - Headline con beneficio claro (+300% conversión)
 * - UN solo CTA principal (múltiples CTAs = -266% conversión)
 * - Social proof con stats de características
 * - FAQ para responder objeciones
 *
 * NOTE: This page is hidden in desktop mode (you're already running the app!)
 */

'use client';

import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import { AppTemplate } from '@/components/layout/AppTemplate';
import { Button } from '@/components/ui/button';
import { detectTauri, isBrowser } from '@/lib/environment';
import { NeuralNetworkCanvas } from '@/components/background/NeuralNetworkCanvas';
import {
  Download,
  Apple,
  Monitor,
  Shield,
  Zap,
  Lock,
  RefreshCw,
  CheckCircle,
  ExternalLink,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Gift,
  WifiOff,
  Stethoscope,
  Mic,
  FileText,
  Brain,
  ClipboardCheck,
  ArrowRight,
  Heart,
  Users,
  Globe,
} from 'lucide-react';

interface Release {
  version: string;
  date: string;
  platforms: {
    macos?: {
      url: string;
      size: string;
      sha256: string;
    };
    windows?: {
      url: string;
      size: string;
      sha256: string;
    };
    linux?: {
      url: string;
      size: string;
      sha256: string;
    };
  };
  changelog?: string[];
}

// Benefits reescritos con enfoque en valor, no características
const benefits = [
  {
    icon: Lock,
    title: 'Privacidad Total',
    description: 'Tus pacientes nunca tocan internet. Cada consulta queda en tu computadora.',
    stat: '0 datos en la nube',
  },
  {
    icon: Zap,
    title: 'Rapidez Extrema',
    description: 'Genera notas SOAP completas en segundos, no en minutos de dictado.',
    stat: 'Notas en segundos',
  },
  {
    icon: Shield,
    title: 'Control Absoluto',
    description: 'IA potente sin pagar $20/mes. Cumple HIPAA sin esfuerzo extra.',
    stat: 'Sin suscripciones',
  },
];

// FAQ para responder objeciones comunes
const faqs = [
  {
    question: '¿Necesito internet para usarlo?',
    answer: 'No. Aurity Desktop funciona 100% offline. La IA corre en tu computadora usando Ollama. Puedes usarlo en consultorios sin conexión.',
  },
  {
    question: '¿Mis datos de pacientes están seguros?',
    answer: 'Absolutamente. Ningún dato sale de tu computadora. No hay servidores externos, no hay nube, no hay transmisión. Todo se almacena localmente con encriptación.',
  },
  {
    question: '¿Cuánto cuesta?',
    answer: 'El programa piloto es gratuito. Estamos buscando médicos que nos den feedback. Después del piloto, será una licencia única (sin suscripción mensual).',
  },
  {
    question: '¿Funciona con mi especialidad médica?',
    answer: 'Sí. Aurity se adapta a cualquier especialidad: medicina general, pediatría, ginecología, cardiología, etc. El modelo de IA entiende terminología médica en español.',
  },
];

const systemRequirements = {
  macos: {
    os: 'macOS 12.0 (Monterey) o posterior',
    cpu: 'Apple Silicon (M1/M2/M3) o Intel',
    ram: '8 GB mínimo, 16 GB recomendado',
    disk: '10 GB de espacio libre',
  },
  windows: {
    os: 'Windows 10 (64-bit) o Windows 11',
    cpu: 'Procesador x86_64',
    ram: '8 GB mínimo, 16 GB recomendado',
    disk: '10 GB de espacio libre',
  },
  linux: {
    os: 'Ubuntu 22.04 LTS o compatible',
    cpu: 'Procesador x86_64',
    ram: '8 GB mínimo, 16 GB recomendado',
    disk: '10 GB de espacio libre',
  },
};

// Releases are loaded from /releases.json (generated by CI/CD)
interface ReleasesData {
  releases: Release[];
  generatedAt: string;
  source: string;
}

// FAQ Accordion Item Component
function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-slate-700 last:border-b-0">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full py-4 sm:py-5 flex items-center justify-between text-left hover:text-emerald-400 transition-colors"
      >
        <span className="text-base sm:text-lg font-medium text-white pr-4">{question}</span>
        {isOpen ? (
          <ChevronUp className="w-5 h-5 text-emerald-400 flex-shrink-0" />
        ) : (
          <ChevronDown className="w-5 h-5 text-slate-400 flex-shrink-0" />
        )}
      </button>
      {isOpen && (
        <div className="pb-4 sm:pb-5 text-slate-300 text-sm sm:text-base leading-relaxed">
          {answer}
        </div>
      )}
    </div>
  );
}

// Demo steps for the Medical AI pipeline
const demoSteps = [
  {
    id: 'dictation',
    icon: Mic,
    label: 'Dictado',
    duration: '2s',
    description: 'El médico habla naturalmente'
  },
  {
    id: 'transcription',
    icon: FileText,
    label: 'Transcripción',
    duration: '1.5s',
    description: 'Voz a texto en tiempo real'
  },
  {
    id: 'analysis',
    icon: Brain,
    label: 'Análisis IA',
    duration: '3s',
    description: 'Extracción de datos clínicos'
  },
  {
    id: 'soap',
    icon: ClipboardCheck,
    label: 'Nota SOAP',
    duration: 'Listo',
    description: 'Nota estructurada lista'
  },
];

// Medical AI Demo Component - Animated Timeline
function MedicalAIDemo() {
  const [activeStep, setActiveStep] = useState(0);
  const [isComplete, setIsComplete] = useState(false);
  const isCleanedUpRef = useRef(false);

  useEffect(() => {
    // Timings for each step (in ms)
    const stepDurations = [2000, 1500, 3000, 1500];
    // Track all timeouts for cleanup
    const timeoutIds: NodeJS.Timeout[] = [];

    const runAnimation = () => {
      if (isCleanedUpRef.current) return; // Don't run if cleanup has occurred

      isCleanedUpRef.current = false; // Reset for new animation cycle
      setActiveStep(0);
      setIsComplete(false);

      let totalDelay = 0;

      stepDurations.forEach((duration, index) => {
        const stepTimeout = setTimeout(() => {
          if (isCleanedUpRef.current) return;
          setActiveStep(index);
          if (index === stepDurations.length - 1) {
            const completeTimeout = setTimeout(() => {
              if (isCleanedUpRef.current) return;
              setIsComplete(true);
            }, duration - 500);
            timeoutIds.push(completeTimeout);
          }
        }, totalDelay);
        timeoutIds.push(stepTimeout);
        totalDelay += duration;
      });

      // Reset and loop after completion
      const loopTimeout = setTimeout(() => {
        if (!isCleanedUpRef.current) {
          runAnimation();
        }
      }, totalDelay + 2000);
      timeoutIds.push(loopTimeout);
    };

    runAnimation();

    // Cleanup: cancel all pending timeouts
    return () => {
      isCleanedUpRef.current = true;
      timeoutIds.forEach(id => clearTimeout(id));
    };
  }, []);

  return (
    <div className="bg-slate-800/80 backdrop-blur-lg rounded-2xl border border-white/10 p-4 sm:p-6 md:p-8 shadow-2xl">
      {/* Header */}
      <div className="text-center mb-6 sm:mb-8">
        <h3 className="text-lg sm:text-xl font-semibold text-white mb-2">
          Así funciona Aurity
        </h3>
        <p className="text-slate-400 text-sm sm:text-base">
          De tu voz a una nota SOAP en segundos
        </p>
      </div>

      {/* Timeline */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-2 sm:gap-0">
        {demoSteps.map((step, index) => {
          const Icon = step.icon;
          const isActive = index === activeStep;
          const isPast = index < activeStep || isComplete;

          return (
            <div key={step.id} className="flex items-center">
              {/* Step */}
              <div className={`
                flex flex-col items-center transition-all duration-500
                ${isActive ? 'scale-110' : 'scale-100'}
              `}>
                {/* Icon Circle */}
                <div className={`
                  w-14 h-14 sm:w-16 sm:h-16 rounded-full flex items-center justify-center
                  transition-all duration-500 relative
                  ${isActive
                    ? 'bg-emerald-500 shadow-lg shadow-emerald-500/50'
                    : isPast
                      ? 'bg-emerald-600/80'
                      : 'bg-slate-700'
                  }
                `}>
                  <Icon className={`
                    w-6 h-6 sm:w-7 sm:h-7 transition-colors duration-300
                    ${isActive || isPast ? 'text-white' : 'text-slate-400'}
                  `} />

                  {/* Pulse animation for active step */}
                  {isActive && (
                    <div className="absolute inset-0 rounded-full bg-emerald-400 animate-ping opacity-30" />
                  )}
                </div>

                {/* Label */}
                <span className={`
                  mt-2 text-xs sm:text-sm font-medium transition-colors duration-300
                  ${isActive ? 'text-emerald-400' : isPast ? 'text-emerald-500/70' : 'text-slate-500'}
                `}>
                  {step.label}
                </span>

                {/* Duration badge */}
                <span className={`
                  mt-1 text-[10px] sm:text-xs px-2 py-0.5 rounded-full transition-all duration-300
                  ${isActive
                    ? 'bg-emerald-500/20 text-emerald-300'
                    : isPast
                      ? 'bg-slate-700/50 text-slate-400'
                      : 'bg-slate-800 text-slate-600'
                  }
                `}>
                  {step.duration}
                </span>
              </div>

              {/* Arrow connector (not after last item) */}
              {index < demoSteps.length - 1 && (
                <div className="hidden sm:flex items-center mx-2 sm:mx-4">
                  <div className={`
                    w-8 sm:w-12 h-0.5 transition-all duration-500
                    ${isPast ? 'bg-emerald-500' : 'bg-slate-700'}
                  `} />
                  <ArrowRight className={`
                    w-4 h-4 -ml-1 transition-colors duration-300
                    ${isPast ? 'text-emerald-500' : 'text-slate-700'}
                  `} />
                </div>
              )}

              {/* Mobile arrow (vertical) */}
              {index < demoSteps.length - 1 && (
                <div className="flex sm:hidden items-center justify-center my-1">
                  <div className={`
                    w-0.5 h-4 transition-all duration-500
                    ${isPast ? 'bg-emerald-500' : 'bg-slate-700'}
                  `} />
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Current step description */}
      <div className="mt-6 sm:mt-8 text-center">
        <div className={`
          inline-flex items-center gap-2 px-4 py-2 rounded-full
          transition-all duration-500
          ${isComplete
            ? 'bg-emerald-500/20 text-emerald-300'
            : 'bg-slate-700/50 text-slate-300'
          }
        `}>
          {isComplete ? (
            <>
              <CheckCircle2 className="w-4 h-4" />
              <span className="text-sm">Nota SOAP lista para revisión</span>
            </>
          ) : (
            <span className="text-sm">{demoSteps[activeStep]?.description}</span>
          )}
        </div>
      </div>
    </div>
  );
}

export default function DownloadsPage() {
  const router = useRouter();
  const [releases, setReleases] = useState<Release[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Direct Tauri detection (stable, no context dependency)
  const isTauri = isBrowser() && detectTauri();

  useEffect(() => {
    // Only fetch releases if NOT in Tauri (web mode)
    if (!isTauri) {
      fetchLatestRelease();
    } else {
      setLoading(false);
    }
  }, [isTauri]);

  const fetchLatestRelease = async () => {
    setLoading(true);
    setError(null);

    try {
      // Fetch releases from static JSON (generated by CI/CD)
      const response = await fetch('/releases.json');
      if (!response.ok) {
        throw new Error(`Error al obtener releases: ${response.status}`);
      }

      const data: ReleasesData = await response.json();

      if (data.releases && data.releases.length > 0) {
        setReleases(data.releases);
      } else {
        setError('No hay releases disponibles');
      }
    } catch (err) {
      console.error('Error fetching releases:', err);
      setError('Error al cargar releases. Por favor intenta más tarde.');
    } finally {
      setLoading(false);
    }
  };

  // Show "already installed" message in desktop mode (Tauri)
  if (isTauri) {
    return (
      <AppTemplate backgroundGradient="none" maxWidth="none">
        <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white dark:from-slate-900 dark:to-slate-800 flex items-center justify-center">
          <div className="text-center p-8 max-w-md">
            <CheckCircle2 className="w-16 h-16 text-green-500 mx-auto mb-4" />
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">
              Ya tienes Aurity Desktop
            </h1>
            <p className="text-slate-600 dark:text-slate-300 mb-6">
              Estás corriendo la aplicación de escritorio.
              No necesitas descargar nada más.
            </p>
            <Button onClick={() => router.push('/chat')}>
              Ir al Chat
            </Button>
          </div>
        </div>
      </AppTemplate>
    );
  }

  const latestRelease = releases[0];

  // Show optimized landing page for ALL users
  return (
      <AppTemplate
        backgroundGradient="none"
        maxWidth="none"
        padding="0"
        showWatermark={true}
      >
        {/* Fixed Navbar Logo */}
        <nav className="fixed top-0 left-0 right-0 z-50 px-6 py-4">
          <Link
            href="/"
            className="inline-block transition-opacity hover:opacity-100"
            aria-label="Volver al hub de AURITY"
          >
            <Image
              src="/logos/aurity-logo-light.png"
              alt="AURITY"
              width={96}
              height={26}
              className="opacity-90 sm:w-24 sm:h-[26px] w-20 h-[21px]"
              priority
            />
          </Link>
        </nav>

        {/* Neural network background animation */}
        <NeuralNetworkCanvas opacity={0.25} />

        <div className="min-h-screen bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900 flex flex-col">
          {/* ============================================
              HERO SECTION (Above the Fold)
              ============================================ */}
          <section className="flex-1 flex flex-col items-center justify-center px-4 py-12 sm:py-16 md:py-20">
            <div className="text-center max-w-4xl mx-auto w-full">
              {/* Hero Wordmark */}
              <div className="mb-8">
                <Image
                  src="/logos/aurity-logo-light.png"
                  alt="AURITY"
                  width={140}
                  height={37}
                  className="mx-auto opacity-60 sm:w-[140px] sm:h-[37px] w-[110px] h-[29px]"
                />
              </div>

              {/* Headline principal - beneficio claro */}
              <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-4 sm:mb-6 leading-tight">
                El Copiloto Médico que Vive en Tu Computadora
              </h1>

              {/* Subheadline con propuesta de valor */}
              <p className="text-lg sm:text-xl md:text-2xl text-slate-300 mb-6 sm:mb-8 px-2 max-w-3xl mx-auto">
                Genera notas SOAP en segundos. 100% offline.
                <br className="hidden sm:block" />
                <span className="text-emerald-400 font-medium">
                  Ningún paciente en la nube. Ninguna suscripción mensual.
                </span>
              </p>

              {/* Trust badges (checkmarks) */}
              <div className="flex flex-wrap justify-center gap-3 sm:gap-6 mb-8 sm:mb-10 text-sm sm:text-base">
                <div className="flex items-center gap-2 text-slate-300">
                  <WifiOff className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-400" />
                  <span>Funciona sin internet</span>
                </div>
                <div className="flex items-center gap-2 text-slate-300">
                  <Lock className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-400" />
                  <span>Tus datos nunca salen de tu PC</span>
                </div>
                <div className="flex items-center gap-2 text-slate-300">
                  <Gift className="w-4 h-4 sm:w-5 sm:h-5 text-emerald-400" />
                  <span>Licencias piloto gratuitas</span>
                </div>
              </div>

              {/* CTA Principal - UN SOLO BOTÓN */}
              {loading ? (
                <div className="flex justify-center py-6 sm:py-8">
                  <RefreshCw className="w-6 h-6 sm:w-8 sm:h-8 animate-spin text-emerald-500" />
                </div>
              ) : error ? (
                <div className="flex flex-col items-center py-6 sm:py-8">
                  <p className="text-red-400 mb-4 text-sm sm:text-base">{error}</p>
                  <Button onClick={fetchLatestRelease} variant="outline" className="border-slate-600 text-slate-300">
                    <RefreshCw className="w-4 h-4 mr-2" />
                    Reintentar
                  </Button>
                </div>
              ) : (
                <div className="space-y-3 sm:space-y-4 px-2">
                  <a
                    className="glass-hero-cta w-full sm:w-auto h-14 sm:h-16 md:h-20 px-8 sm:px-10 md:px-14 text-lg sm:text-xl md:text-2xl text-white rounded-xl flex items-center justify-center gap-2 sm:gap-3 cursor-pointer"
                    href={(() => {
                      // Detect OS and return appropriate download URL
                      if (typeof navigator === 'undefined') return '#';
                      const ua = navigator.userAgent.toLowerCase();
                      if (ua.includes('mac')) {
                        return latestRelease?.platforms.macos?.url || '#';
                      } else if (ua.includes('win')) {
                        return latestRelease?.platforms.windows?.url || '#';
                      } else if (ua.includes('linux')) {
                        return latestRelease?.platforms.linux?.url || '#';
                      }
                      return latestRelease?.platforms.windows?.url || '#';
                    })()}
                    download
                  >
                    <Download className="w-5 h-5 sm:w-6 sm:h-6 md:w-8 md:h-8" />
                    Descargar Gratis
                  </a>
                  {latestRelease && (
                    <p className="text-slate-400 text-xs sm:text-sm">
                      Versión {latestRelease.version} · macOS, Windows y Linux
                    </p>
                  )}
                </div>
              )}
            </div>
          </section>

          {/* ============================================
              DEMO VISUAL SECTION - Animated Timeline
              ============================================ */}
          <section className="px-4 pb-12 sm:pb-16">
            <div className="max-w-4xl mx-auto">
              <MedicalAIDemo />
            </div>
          </section>

          {/* ============================================
              FREE INTELLIGENCE PHILOSOPHY SECTION
              ============================================ */}
          <section className="bg-gradient-to-b from-slate-800/50 to-slate-900/50 py-12 sm:py-16 md:py-20 px-4">
            <div className="max-w-4xl mx-auto">
              {/* Section Header */}
              <div className="text-center mb-10 sm:mb-14">
                <div className="inline-flex items-center gap-2 bg-emerald-500/10 backdrop-blur-sm text-emerald-400 px-4 py-1.5 rounded-full text-sm font-medium mb-4 border border-emerald-400/20">
                  <Heart className="w-4 h-4" />
                  Nuestra Filosofía
                </div>
                <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-4">
                  Free Intelligence
                </h2>
                <p className="text-slate-300 text-base sm:text-lg max-w-2xl mx-auto">
                  Creemos que la inteligencia artificial médica debe ser libre, privada y accesible para todos.
                </p>
              </div>

              {/* Philosophy Cards */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 sm:gap-8">
                {/* Soberanía de Datos */}
                <div className="glass-card-feature p-6">
                  <div className="w-12 h-12 bg-emerald-500/20 backdrop-blur-sm rounded-lg flex items-center justify-center mb-4 border border-emerald-400/10">
                    <Lock className="w-6 h-6 text-emerald-400" />
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-2">
                    Soberanía de Datos
                  </h3>
                  <p className="text-slate-400 text-sm leading-relaxed">
                    Tus datos clínicos son tuyos. No los vendemos, no los analizamos, no los compartimos.
                    Corren en <strong className="text-slate-300">tu hardware</strong>, bajo <strong className="text-slate-300">tu control</strong>.
                  </p>
                </div>

                {/* IA para Todos */}
                <div className="glass-card-feature p-6">
                  <div className="w-12 h-12 bg-emerald-500/20 backdrop-blur-sm rounded-lg flex items-center justify-center mb-4 border border-emerald-400/10">
                    <Users className="w-6 h-6 text-emerald-400" />
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-2">
                    IA para Todos
                  </h3>
                  <p className="text-slate-400 text-sm leading-relaxed">
                    La tecnología médica avanzada no debería ser exclusiva de grandes hospitales.
                    Cualquier consultorio merece herramientas de <strong className="text-slate-300">clase mundial</strong>.
                  </p>
                </div>

                {/* Sin Dependencias */}
                <div className="glass-card-feature p-6">
                  <div className="w-12 h-12 bg-emerald-500/20 backdrop-blur-sm rounded-lg flex items-center justify-center mb-4 border border-emerald-400/10">
                    <Globe className="w-6 h-6 text-emerald-400" />
                  </div>
                  <h3 className="text-lg font-semibold text-white mb-2">
                    Sin Dependencias
                  </h3>
                  <p className="text-slate-400 text-sm leading-relaxed">
                    Sin internet, sin servidores externos, sin suscripciones mensuales.
                    Aurity funciona donde tú trabajes, <strong className="text-slate-300">siempre disponible</strong>.
                  </p>
                </div>
              </div>

              {/* Bottom Statement */}
              <div className="mt-10 sm:mt-14 text-center">
                <p className="text-slate-400 text-sm sm:text-base max-w-2xl mx-auto italic">
                  &ldquo;La privacidad del paciente no es una feature premium. Es un derecho fundamental.&rdquo;
                </p>
              </div>
            </div>
          </section>

          {/* ============================================
              BENEFITS SECTION (3 cards)
              ============================================ */}
          <section className="bg-slate-800/50 py-12 sm:py-16 md:py-20 px-4">
            <div className="max-w-5xl mx-auto">
              <h2 className="text-2xl sm:text-3xl font-bold text-white text-center mb-8 sm:mb-12">
                Por qué los médicos eligen Aurity
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 sm:gap-6 md:gap-8">
                {benefits.map((benefit) => (
                  <div
                    key={benefit.title}
                    className="glass-card-feature p-5 sm:p-6"
                  >
                    <div className="flex items-center gap-3 mb-3">
                      <div className="w-10 h-10 sm:w-12 sm:h-12 bg-emerald-500/20 backdrop-blur-sm rounded-lg flex items-center justify-center border border-emerald-400/10">
                        <benefit.icon className="w-5 h-5 sm:w-6 sm:h-6 text-emerald-400" />
                      </div>
                      <span className="text-emerald-400 text-xs sm:text-sm font-medium">
                        {benefit.stat}
                      </span>
                    </div>
                    <h3 className="text-lg sm:text-xl font-semibold text-white mb-2">
                      {benefit.title}
                    </h3>
                    <p className="text-slate-400 text-sm sm:text-base">
                      {benefit.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* ============================================
              DOWNLOAD CARDS SECTION
              ============================================ */}
          <section className="py-12 sm:py-16 px-4">
            <div className="max-w-5xl mx-auto">
              <h2 className="text-2xl sm:text-3xl font-bold text-white text-center mb-3">
                Disponible para tu plataforma
              </h2>
              <p className="text-slate-400 text-center mb-8 sm:mb-12">
                Instalación simple, sin configuración complicada
              </p>

              {!loading && !error && latestRelease && (
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
                  {/* macOS */}
                  <div className="glass-card-feature p-5 sm:p-6">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-12 h-12 bg-slate-700/80 backdrop-blur-sm rounded-xl flex items-center justify-center border border-white/5">
                        <Apple className="w-7 h-7 text-slate-300" />
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">macOS</h3>
                        <p className="text-slate-500 text-sm">Apple Silicon e Intel</p>
                      </div>
                    </div>
                    {latestRelease.platforms.macos ? (
                      <a
                        className="glass-button-interactive w-full h-11 text-white rounded-lg flex items-center justify-center gap-2 cursor-pointer"
                        href={latestRelease.platforms.macos.url !== '#coming-soon' ? latestRelease.platforms.macos.url : undefined}
                        download
                      >
                        <Download className="w-4 h-4" />
                        {latestRelease.platforms.macos.url === '#coming-soon'
                          ? 'Próximamente'
                          : `Descargar DMG`}
                      </a>
                    ) : (
                      <p className="text-slate-500 text-sm">Aún no disponible</p>
                    )}
                  </div>

                  {/* Windows */}
                  <div className="glass-card-feature p-5 sm:p-6">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-12 h-12 bg-slate-700/80 backdrop-blur-sm rounded-xl flex items-center justify-center border border-white/5">
                        <Monitor className="w-7 h-7 text-slate-300" />
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">Windows</h3>
                        <p className="text-slate-500 text-sm">Windows 10/11 (64-bit)</p>
                      </div>
                    </div>
                    {latestRelease.platforms.windows ? (
                      <a
                        className="glass-button-interactive w-full h-11 text-white rounded-lg flex items-center justify-center gap-2 cursor-pointer"
                        href={latestRelease.platforms.windows.url !== '#coming-soon' ? latestRelease.platforms.windows.url : undefined}
                        download
                      >
                        <Download className="w-4 h-4" />
                        {latestRelease.platforms.windows.url === '#coming-soon'
                          ? 'Próximamente'
                          : `Descargar EXE`}
                      </a>
                    ) : (
                      <p className="text-slate-500 text-sm">Aún no disponible</p>
                    )}
                  </div>

                  {/* Linux */}
                  <div className="glass-card-feature p-5 sm:p-6 sm:col-span-2 lg:col-span-1">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-12 h-12 bg-slate-700/80 backdrop-blur-sm rounded-xl flex items-center justify-center border border-white/5">
                        <Monitor className="w-7 h-7 text-slate-300" />
                      </div>
                      <div>
                        <h3 className="text-lg font-semibold text-white">Linux</h3>
                        <p className="text-slate-500 text-sm">AppImage (x86_64)</p>
                      </div>
                    </div>
                    {latestRelease.platforms.linux ? (
                      <a
                        className="glass-button-interactive w-full h-11 text-white rounded-lg flex items-center justify-center gap-2 cursor-pointer"
                        href={latestRelease.platforms.linux.url !== '#coming-soon' ? latestRelease.platforms.linux.url : undefined}
                        download
                      >
                        <Download className="w-4 h-4" />
                        {latestRelease.platforms.linux.url === '#coming-soon'
                          ? 'Próximamente'
                          : `Descargar AppImage`}
                      </a>
                    ) : (
                      <p className="text-slate-500 text-sm">Aún no disponible</p>
                    )}
                  </div>
                </div>
              )}
            </div>
          </section>

          {/* ============================================
              FAQ SECTION
              ============================================ */}
          <section className="bg-slate-800/30 py-12 sm:py-16 md:py-20 px-4">
            <div className="max-w-3xl mx-auto">
              <h2 className="text-2xl sm:text-3xl font-bold text-white text-center mb-8 sm:mb-12">
                Preguntas Frecuentes
              </h2>
              <div className="glass-background px-4 sm:px-6">
                {faqs.map((faq, index) => (
                  <FAQItem key={index} question={faq.question} answer={faq.answer} />
                ))}
              </div>
            </div>
          </section>

          {/* ============================================
              FINAL CTA SECTION (Urgencia/Escasez)
              ============================================ */}
          <section className="py-12 sm:py-16 md:py-20 px-4">
            <div className="max-w-3xl mx-auto text-center">
              {/* Badge de urgencia */}
              <div className="inline-flex items-center gap-2 bg-emerald-500/20 backdrop-blur-sm text-emerald-400 px-4 py-2 rounded-full text-sm font-medium mb-6 border border-emerald-400/20">
                <Gift className="w-4 h-4" />
                Licencias Piloto Limitadas
              </div>

              <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-white mb-4">
                Sé parte de los primeros en usarlo
              </h2>
              <p className="text-slate-300 text-base sm:text-lg mb-8 max-w-2xl mx-auto">
                Estamos aceptando médicos para el programa piloto.
                <br className="hidden sm:block" />
                Acceso gratuito a cambio de tu feedback.
              </p>

              {!loading && !error && (
                <a
                  className="glass-hero-cta h-14 sm:h-16 px-8 sm:px-12 text-lg sm:text-xl text-white rounded-xl inline-flex items-center justify-center gap-2 sm:gap-3 cursor-pointer"
                  href={(() => {
                    if (typeof navigator === 'undefined') return '#';
                    const ua = navigator.userAgent.toLowerCase();
                    if (ua.includes('mac')) {
                      return latestRelease?.platforms.macos?.url || '#';
                    } else if (ua.includes('win')) {
                      return latestRelease?.platforms.windows?.url || '#';
                    } else if (ua.includes('linux')) {
                      return latestRelease?.platforms.linux?.url || '#';
                    }
                    return latestRelease?.platforms.windows?.url || '#';
                  })()}
                  download
                >
                  <Download className="w-5 h-5 sm:w-6 sm:h-6" />
                  Obtener Mi Licencia Piloto
                </a>
              )}

              {/* Ollama requirement note */}
              <div className="mt-8 p-4 bg-slate-800/50 rounded-lg border border-slate-700 text-left max-w-xl mx-auto">
                <p className="text-slate-400 text-sm">
                  <strong className="text-white">Requisito:</strong> Aurity Desktop usa{' '}
                  <a
                    href="https://ollama.ai"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-emerald-400 hover:underline inline-flex items-center gap-1"
                  >
                    Ollama <ExternalLink className="w-3 h-3" />
                  </a>{' '}
                  para IA local. Instálalo primero, luego ejecuta{' '}
                  <code className="bg-slate-700 px-1.5 py-0.5 rounded text-xs text-emerald-300">
                    ollama pull qwen3:8b
                  </code>
                </p>
              </div>
            </div>
          </section>

          {/* Footer minimal */}
          <footer className="border-t border-slate-800 py-6 px-4">
            <p className="text-center text-slate-500 text-sm">
              Aurity Desktop · Privacidad primero, siempre.
            </p>
          </footer>
        </div>
      </AppTemplate>
    );
}
