/**
 * Releases API Route
 *
 * NOTE: This API route is deprecated.
 * The /downloads page now reads directly from /releases.json (static file).
 * releases.json is auto-generated by CI/CD when a new release is created.
 *
 * This route is kept for backward compatibility but simply redirects to the static file.
 */

import { NextResponse } from 'next/server';

// Required for static export
export const dynamic = 'force-static';

export async function GET() {
  // Redirect to static releases.json
  return NextResponse.json({
    message: 'This API is deprecated. Use /releases.json directly.',
    redirect: '/releases.json',
  });
}
