# Free Intelligence — Decision Rules (Policy Engine)
# JSON-based if/then rules for automated decisions

version: 1

rules:
  # Triage red → high risk event
  - name: "triage_red_high_risk"
    enabled: true
    condition:
      field: "output.triage"
      operator: "equals"
      value: "red"
    action:
      type: "emit_event"
      event: "DECISION_APPLIED"
      metadata:
        risk: "high"

  # PII detected → quarantine and redact
  - name: "pii_quarantine"
    enabled: true
    condition:
      field: "output.contains_pii"
      operator: "equals"
      value: true
    action:
      type: "quarantine"
      redact: true
      metadata:
        reason: "pii_detected"

  # Latency breach → SLO warning
  - name: "latency_slo_breach"
    enabled: true
    condition:
      field: "latency_ms"
      operator: "greater_than"
      value: 2000
    action:
      type: "emit_event"
      event: "SLO_BREACH"
      severity: "warn"
      metadata:
        threshold_ms: 2000

  # Existing rules below
  # Auto-archive old sessions
  - name: "auto_archive_old_sessions"
    enabled: true
    condition:
      field: "session.created_at"
      operator: "older_than"
      value: "180d"
    action:
      type: "archive"
      target: "session"
      metadata:
        reason: "auto_archive_policy"

  # Reject large exports
  - name: "reject_large_export"
    enabled: true
    condition:
      field: "export.size_mb"
      operator: "greater_than"
      value: 500
    action:
      type: "reject"
      message: "Export size exceeds 500MB limit. Use pagination."

  # Enable fallback LLM on high latency
  - name: "fallback_llm_on_latency"
    enabled: true
    condition:
      field: "llm.p95_latency_ms"
      operator: "greater_than"
      value: 5000
    action:
      type: "route"
      target: "llm_fallback"
      model: "ollama/llama3:8b"

  # Alert on error budget exhaustion
  - name: "alert_error_budget_low"
    enabled: true
    condition:
      field: "error_budget.remaining"
      operator: "less_than"
      value: 0.1
    action:
      type: "alert"
      channel: "slack"
      severity: "critical"
      message: "Error budget <10% for {{ service_name }}"

  # Auto-cleanup old audit logs
  - name: "cleanup_old_audit_logs"
    enabled: true
    condition:
      field: "audit_log.created_at"
      operator: "older_than"
      value: "90d"
    action:
      type: "delete"
      target: "audit_log"
      metadata:
        reason: "retention_policy"

  # Block mutation without event
  - name: "block_mutation_without_event"
    enabled: true
    condition:
      field: "mutation.has_event"
      operator: "equals"
      value: false
    action:
      type: "reject"
      message: "Mutations require canonical event. Use event-sourced architecture."

  # Trigger chaos drill on low error rate
  - name: "trigger_chaos_drill"
    enabled: false  # Manual trigger only
    condition:
      field: "error_budget.remaining"
      operator: "greater_than"
      value: 0.9
    action:
      type: "trigger_chaos"
      scenario: "random"
      metadata:
        reason: "proactive_resilience_testing"
