# Free Intelligence — Master Policy Configuration
# Consolidates all executable policies

version: "1.0"

# Sovereignty Policy
sovereignty:
  egress:
    default: deny

# Privacy Policy
privacy:
  phi:
    enabled: false
  redaction:
    spoilers: true
    style_file: "config/redaction_style.yaml"

# Integrity Policy
integrity:
  segment_seconds: 60
  hash: sha256
  snapshots:
    ready:
      daily: 7

# LLM Policy
llm:
  enabled: true
  providers: ["claude", "ollama"]
  budgets:
    monthly_usd: 200
  timeouts:
    request_ms: 8000
  retry: 1
  audit:
    required: true
    decorator: "@require_audit_log"
  fallback:
    enabled: true
    model: "ollama/llama3:8b"

# Timeline Policy
timeline:
  auto:
    enabled: false  # Feature flag
  auto_archive_days: 180
  max_interactions_per_query: 1000
  pagination_default: 50

# Agents Policy
agents:
  enabled: false

# Reactions to Policy Violations
reactions:
  policy_violation: ["quarantine", "audit", "alert_warn"]

# Mutation Policy
mutation:
  append_only: true
  validator: "backend.mutation_validator"
  event_required: true

# Corpus Policy
corpus:
  identity_required: true
  owner_hash_algorithm: "sha256"
  lock_timeout_seconds: 30

# Export Policy
export:
  enabled: true
  formats: ["json", "markdown", "hdf5"]
  manifest_required: true
  hash_algorithm: "sha256"

# Retention Policy
retention:
  audit_logs_days: 90
  session_min_days: 365
  export_manifests_days: 730

# Security Policy
security:
  lan_only: true
  auth_required: true
  rbac_enabled: true

# Observability Policy
observability:
  error_budgets_file: "observability/error_budgets.yaml"
  alerts_file: "observability/alerts.prom"
  chaos_drills_enabled: true
