"""initial_schema

Revision ID: d53f042798a1
Revises:
Create Date: 2025-12-30 21:40:12.548890

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d53f042798a1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinics",
        sa.Column("clinic_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("specialty", sa.String(length=100), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("primary_color", sa.String(length=7), nullable=True),
        sa.Column("welcome_message", sa.Text(), nullable=True),
        sa.Column("checkin_qr_enabled", sa.Boolean(), nullable=True),
        sa.Column("chat_enabled", sa.Boolean(), nullable=True),
        sa.Column("payments_enabled", sa.Boolean(), nullable=True),
        sa.Column("whatsapp_enabled", sa.Boolean(), nullable=True),
        sa.Column("subscription_plan", sa.String(length=50), nullable=True),
        sa.Column("subscription_valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("clinic_id"),
    )
    op.create_table(
        "patients",
        sa.Column("patient_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("apellido", sa.String(length=100), nullable=False),
        sa.Column("fecha_nacimiento", sa.DateTime(), nullable=False),
        sa.Column(
            "genero",
            sa.Enum("MASCULINO", "FEMENINO", "OTRO", "NO_ESPECIFICADO", name="gender_enum"),
            nullable=True,
        ),
        sa.Column("curp", sa.CHAR(length=18), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("patient_id"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_patients_apellido"), ["apellido"], unique=False)
        batch_op.create_index(batch_op.f("ix_patients_curp"), ["curp"], unique=True)
        batch_op.create_index(batch_op.f("ix_patients_nombre"), ["nombre"], unique=False)

    op.create_table(
        "providers",
        sa.Column("provider_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("cedula_profesional", sa.CHAR(length=20), nullable=True),
        sa.Column("especialidad", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("provider_id"),
    )
    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_providers_cedula_profesional"), ["cedula_profesional"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_providers_nombre"), ["nombre"], unique=False)

    op.create_table(
        "user_persona_configs",
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("persona_id", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=True),
        sa.Column("custom_prompt", sa.Text(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("voice", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "persona_id"),
    )
    op.create_table(
        "checkin_sessions",
        sa.Column("session_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("clinic_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "current_step",
            sa.Enum(
                "SCAN_QR",
                "IDENTIFY",
                "CONFIRM_IDENTITY",
                "PENDING_ACTIONS",
                "SUCCESS",
                "ERROR",
                name="checkinstep",
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("identification_method", sa.String(length=20), nullable=True),
        sa.Column("appointment_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("patient_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "device_type", sa.Enum("MOBILE", "KIOSK", "TABLET", name="devicetype"), nullable=False
        ),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("identification_attempts", sa.Integer(), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.clinic_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("checkin_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_checkin_sessions_expires", ["expires_at"], unique=False)

    op.create_table(
        "doctors",
        sa.Column("doctor_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("clinic_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("auth0_user_id", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "clinic_role",
            sa.Enum("OWNER", "ADMIN", "DOCTOR", "STAFF", name="clinicrole"),
            nullable=False,
        ),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("apellido", sa.String(length=100), nullable=False),
        sa.Column("cedula_profesional", sa.String(length=20), nullable=True),
        sa.Column("especialidad", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=150), nullable=True),
        sa.Column("photo_url", sa.String(length=500), nullable=True),
        sa.Column("avg_consultation_minutes", sa.Integer(), nullable=True),
        sa.Column("work_start_time", sa.String(length=5), nullable=True),
        sa.Column("work_end_time", sa.String(length=5), nullable=True),
        sa.Column("working_hours", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.clinic_id"],
        ),
        sa.PrimaryKeyConstraint("doctor_id"),
        sa.UniqueConstraint("cedula_profesional"),
    )
    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doctors_auth0_user_id"), ["auth0_user_id"], unique=True
        )

    op.create_table(
        "waiting_room_events",
        sa.Column("event_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("clinic_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_data", sa.Text(), nullable=True),
        sa.Column("appointment_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("patient_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.clinic_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    with op.batch_alter_table("waiting_room_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_waiting_room_events_clinic_time", ["clinic_id", "created_at"], unique=False
        )

    op.create_table(
        "appointments",
        sa.Column("appointment_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("clinic_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("patient_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("doctor_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estimated_duration", sa.Integer(), nullable=True),
        sa.Column(
            "appointment_type",
            sa.Enum(
                "FIRST_VISIT",
                "FOLLOW_UP",
                "PROCEDURE",
                "EMERGENCY",
                "TELEMEDICINE",
                name="appointmenttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "CONFIRMED",
                "CHECKED_IN",
                "IN_PROGRESS",
                "COMPLETED",
                "NO_SHOW",
                "CANCELLED",
                name="appointmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("called_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checkin_code", sa.String(length=6), nullable=False),
        sa.Column("checkin_code_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("queue_position", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clinic_id"],
            ["clinics.clinic_id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.doctor_id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.patient_id"],
        ),
        sa.PrimaryKeyConstraint("appointment_id"),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appointments_checkin_code"), ["checkin_code"], unique=False
        )
        batch_op.create_index(
            "ix_appointments_checkin_lookup",
            ["clinic_id", "checkin_code", "checkin_code_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_appointments_clinic_date", ["clinic_id", "scheduled_at"], unique=False
        )
        batch_op.create_index(
            "ix_appointments_clinic_status", ["clinic_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_appointments_scheduled_at"), ["scheduled_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_appointments_status"), ["status"], unique=False)

    op.create_table(
        "pending_actions",
        sa.Column("action_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("appointment_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "UPDATE_CONTACT",
                "UPDATE_INSURANCE",
                "SIGN_CONSENT",
                "SIGN_PRIVACY",
                "PAY_COPAY",
                "PAY_BALANCE",
                "UPLOAD_LABS",
                "UPLOAD_IMAGING",
                "FILL_QUESTIONNAIRE",
                "VERIFY_IDENTITY",
                name="pendingactiontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "SKIPPED", name="pendingactionstatus"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=True),
        sa.Column("is_blocking", sa.Boolean(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("payment_intent_id", sa.String(length=100), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("document_url", sa.String(length=500), nullable=True),
        sa.Column("signature_data", sa.Text(), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploaded_file_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("uploaded_file_url", sa.String(length=500), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.appointment_id"],
        ),
        sa.PrimaryKeyConstraint("action_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pending_actions")
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_status"))
        batch_op.drop_index(batch_op.f("ix_appointments_scheduled_at"))
        batch_op.drop_index("ix_appointments_clinic_status")
        batch_op.drop_index("ix_appointments_clinic_date")
        batch_op.drop_index("ix_appointments_checkin_lookup")
        batch_op.drop_index(batch_op.f("ix_appointments_checkin_code"))

    op.drop_table("appointments")
    with op.batch_alter_table("waiting_room_events", schema=None) as batch_op:
        batch_op.drop_index("ix_waiting_room_events_clinic_time")

    op.drop_table("waiting_room_events")
    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctors_auth0_user_id"))

    op.drop_table("doctors")
    with op.batch_alter_table("checkin_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_checkin_sessions_expires")

    op.drop_table("checkin_sessions")
    op.drop_table("user_persona_configs")
    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_providers_nombre"))
        batch_op.drop_index(batch_op.f("ix_providers_cedula_profesional"))

    op.drop_table("providers")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patients_nombre"))
        batch_op.drop_index(batch_op.f("ix_patients_curp"))
        batch_op.drop_index(batch_op.f("ix_patients_apellido"))

    op.drop_table("patients")
    op.drop_table("clinics")
    # ### end Alembic commands ###
