// Environment Variables — persistence for Ollama env config.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// A key-value environment variable pair.
#[derive(Serialize, Deserialize, Clone)]
pub(crate) struct EnvVar {
    key: String,
    value: String,
}

/// Default Ollama environment variables when no config file exists.
fn default_env_vars() -> Vec<EnvVar> {
    vec![
        EnvVar {
            key: "OLLAMA_NUM_PARALLEL".to_string(),
            value: "1".to_string(),
        },
        EnvVar {
            key: "OLLAMA_MAX_LOADED_MODELS".to_string(),
            value: "1".to_string(),
        },
        EnvVar {
            key: "OLLAMA_ORIGINS".to_string(),
            value: "*".to_string(),
        },
    ]
}

/// Path to the Ollama environment file (~/.config/fi-monitor/ollama.env).
fn get_env_file_path() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join("fi-monitor")
        .join("ollama.env")
}

/// Read Ollama environment variables from the config file.
#[tauri::command]
pub(crate) fn get_env_vars() -> Result<Vec<EnvVar>, String> {
    let env_path = get_env_file_path();

    if !env_path.exists() {
        return Ok(default_env_vars());
    }

    let content = std::fs::read_to_string(&env_path)
        .map_err(|e| format!("Failed to read env file: {}", e))?;

    let vars: Vec<EnvVar> = content
        .lines()
        .filter(|line| !line.trim().is_empty() && !line.starts_with('#'))
        .filter_map(|line| {
            let parts: Vec<&str> = line.splitn(2, '=').collect();
            if parts.len() == 2 {
                Some(EnvVar {
                    key: parts[0].trim().to_string(),
                    value: parts[1].trim().to_string(),
                })
            } else {
                None
            }
        })
        .collect();

    Ok(vars)
}

/// Write Ollama environment variables to the config file.
#[tauri::command]
pub(crate) fn set_env_vars(vars: Vec<EnvVar>) -> Result<(), String> {
    let env_path = get_env_file_path();

    if let Some(parent) = env_path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create config dir: {}", e))?;
    }

    let mut content = String::from("# Ollama Environment Variables\n");
    content.push_str("# Generated by FI Monitor\n\n");

    for var in vars {
        content.push_str(&format!("{}={}\n", var.key, var.value));
    }

    std::fs::write(&env_path, content)
        .map_err(|e| format!("Failed to write env file: {}", e))?;

    println!(
        "[FI Monitor] Environment variables saved to {:?}",
        env_path
    );
    Ok(())
}
