import { describe, it, expect, beforeEach } from 'vitest';
import { buildAppointmentSchedulerConfig, Doctor, Appointment, type NonWorkingTimeRange } from '@/components/bryntum/utils/config-builders';
import type { BryntumSchedulerConfig } from '@/components/bryntum/types/scheduler.types';

// Define the type for time range objects based on the structure generated by generateNonWorkingTimeRanges
interface TimeRange extends NonWorkingTimeRange {
  startDate: Date;
  endDate: Date;
}

// Define the type for resource objects based on BryntumResource
interface Resource {
  id: string;
  name: string;
  specialty?: string;
  eventColor?: string;
  [key: string]: unknown;
}

const baseDoctors: Doctor[] = [
  {
    doctor_id: 'doc-weekly',
    nombre: 'Weekly',
    apellido: 'Worker',
    display_name: 'Weekly Worker',
    especialidad: 'Cardio',
    avg_consultation_minutes: 30,
    work_start_time: null,
    work_end_time: null,
    working_hours: [
      { day: 1, start: '09:00', end: '13:00' },
      { day: 1, start: '14:00', end: '18:00' },
    ],
  },
  {
    doctor_id: 'doc-override',
    nombre: 'Override',
    apellido: 'Closed',
    display_name: 'Closed Day',
    especialidad: 'Pedia',
    avg_consultation_minutes: 25,
    work_start_time: '08:00',
    work_end_time: '16:00',
    working_hours: [
      { date: '2025-01-06', day: 1, start: '', end: '', fullDayClosed: true },
    ],
  },
  {
    doctor_id: 'doc-legacy',
    nombre: 'Legacy',
    apellido: 'Derived',
    display_name: 'Legacy Derived',
    especialidad: 'Derm',
    avg_consultation_minutes: 20,
    work_start_time: '10:00',
    work_end_time: '18:00',
    working_hours: [],
  },
];

describe('config-builders appointment scheduler', () => {
  beforeEach(() => {
    process.env.CLINIC_TZ = 'America/Mexico_City';
  });

  it('generates non-working ranges using normalized working hours with overrides and legacy fallback', () => {
    const currentDate = new Date('2025-01-06T12:00:00.000Z');
    const config: BryntumSchedulerConfig = buildAppointmentSchedulerConfig({
      viewMode: 'day',
      currentDate,
      doctors: baseDoctors,
      appointments: [] as Appointment[],
    });

    expect(config.resources).toHaveLength(3);
    expect(config.timeRanges.length).toBeGreaterThan(0);

    const overrideRanges = config.timeRanges.filter((r: TimeRange) => r.resourceId === 'doc-override');
    expect(overrideRanges.some((r: TimeRange) => r.startDate.getDate() === 6)).toBe(true);

    const legacyResource = config.resources.find((r: Resource) => r.id === 'doc-legacy');
    expect(legacyResource).toBeDefined();
  });
});
