/**
 * Export Evidence Utility - Phase 7 (FI-ONBOARD-008)
 *
 * Generate onboarding completion reports in multiple formats:
 * - Markdown (.md)
 * - JSON (.json)
 * - HTML (for PDF printing)
 */

import type { UserRole, ClinicType, AIExperience } from '@aurity-standalone/types/assistant';

export interface OnboardingEvidence {
  user: {
    role?: UserRole;
    clinicType?: ClinicType;
    consultasPerDay?: string;
    aiExperience?: AIExperience;
  };
  philosophy: {
    glitchScore?: number;
    betaScore?: number;
    residenciaScore?: number;
  };
  patient: {
    nombre?: string;
    edad?: number | '';
    genero?: string;
    motivoConsulta?: string;
  };
  consultation: {
    mode?: 'auto' | 'guided' | 'hands-on';
    timeSpent?: number; // seconds
    stepsCompleted?: number;
  };
  conversation: {
    totalMessages?: number;
    fiTones?: string[];
  };
  completedAt: string;
  sessionId: string;
}

/**
 * Generate Markdown export
 */
export function generateMarkdownExport(evidence: OnboardingEvidence): string {
  const md = `# AURITY Onboarding Completion Report

**Session ID:** \`${evidence.sessionId}\`
**Completed At:** ${new Date(evidence.completedAt).toLocaleString('es-MX', {
  timeZone: 'America/Mexico_City',
  dateStyle: 'full',
  timeStyle: 'long'
})}

---

## 📋 User Profile

- **Role:** ${evidence.user.role || 'Not specified'}
- **Clinic Type:** ${evidence.user.clinicType || 'Not specified'}
- **Consultas/day:** ${evidence.user.consultasPerDay || 'Not specified'}
- **AI Experience:** ${evidence.user.aiExperience || 'Not specified'}

---

## 🧠 Philosophy Quiz Results

### Glitch Elegante (Materia)
**Score:** ${evidence.philosophy.glitchScore || 0}/100
**Concept:** Error budgets, SLO 99.9%, tolerance for imperfection

### Beta Permanente (Humano)
**Score:** ${evidence.philosophy.betaScore || 0}/100
**Concept:** Continuous iteration, micro-coaching, never stop learning

### Residencia (Dios Full-Stack)
**Score:** ${evidence.philosophy.residenciaScore || 0}/100
**Concept:** Data sovereignty, local-first, append-only HDF5

---

## 👤 Patient Demo Data

- **Nombre:** ${evidence.patient.nombre || 'Not created'}
- **Edad:** ${evidence.patient.edad ? `${evidence.patient.edad} años` : 'Not specified'}
- **Género:** ${evidence.patient.genero || 'Not specified'}
${evidence.patient.motivoConsulta ? `- **Motivo:** ${evidence.patient.motivoConsulta}` : ''}

${evidence.patient.nombre ? `
**Session ID Format:** \`session_YYYYMMDD_HHMMSS\`
**Storage:** \`/storage/corpus.h5\` (append-only, AES-GCM-256 encrypted)
` : ''}

---

## 🎬 Consultation Simulation

- **Mode:** ${evidence.consultation.mode ? evidence.consultation.mode.toUpperCase() : 'Not completed'}
- **Time Spent:** ${evidence.consultation.timeSpent ? `${Math.round(evidence.consultation.timeSpent / 60)}m ${evidence.consultation.timeSpent % 60}s` : 'N/A'}
- **Steps Completed:** ${evidence.consultation.stepsCompleted || 0}/7

**Simulated Flow:**
1. ✅ Upload chunks (6 chunks)
2. ✅ Checkpoint (concatenate audio)
3. ✅ Transcription (Deepgram/Azure Whisper)
4. ✅ Diarization (Azure GPT-4)
5. ✅ SOAP Generation (Claude Sonnet 4.5)
6. ✅ Export Evidence
7. ✅ Complete

---

## 💬 FI Conversation History

- **Total Messages:** ${evidence.conversation.totalMessages || 0}
- **FI Tones Used:** ${evidence.conversation.fiTones?.join(', ') || 'None'}

---

## 🏆 Achievements

- ✅ **Onboarding Pioneer:** Completed full AURITY onboarding flow
- ✅ **Philosophy Master:** Understood Glitch, Beta, and Residencia concepts
- ✅ **Hands-on Learner:** Experimented with consultation simulation
- ✅ **Data Sovereign:** Learned about local-first architecture

---

## 📊 Onboarding Stats

**Total Phases:** 8/8 completed
**Estimated Time:** 15-30 minutes
**Completion Rate:** 100%

---

**Generated by Free-Intelligence AURITY System**
**Version:** 0.1.0 (Production)
**Architecture:** Local-first, HDF5, FastAPI + Next.js 16

---

> _"Materia = Glitch, Humano = Beta, Residencia = Soberanía, Gnóstico = Tester."_
> — Free-Intelligence
`;

  return md;
}

/**
 * Generate JSON export
 */
export function generateJSONExport(evidence: OnboardingEvidence): string {
  const data = {
    version: "1.0",
    type: "aurity_onboarding_evidence",
    sessionId: evidence.sessionId,
    completedAt: evidence.completedAt,
    completedAtISO: new Date(evidence.completedAt).toISOString(),
    user: {
      role: evidence.user.role || null,
      clinicType: evidence.user.clinicType || null,
      consultasPerDay: evidence.user.consultasPerDay || null,
      aiExperience: evidence.user.aiExperience || null,
    },
    philosophy: {
      glitch: {
        score: evidence.philosophy.glitchScore || 0,
        concept: "Error budgets, SLO 99.9%, tolerance for imperfection",
      },
      beta: {
        score: evidence.philosophy.betaScore || 0,
        concept: "Continuous iteration, micro-coaching, never stop learning",
      },
      residencia: {
        score: evidence.philosophy.residenciaScore || 0,
        concept: "Data sovereignty, local-first, append-only HDF5",
      },
    },
    patient: {
      created: !!evidence.patient.nombre,
      nombre: evidence.patient.nombre || null,
      edad: evidence.patient.edad || null,
      genero: evidence.patient.genero || null,
      motivoConsulta: evidence.patient.motivoConsulta || null,
    },
    consultation: {
      completed: !!evidence.consultation.mode,
      mode: evidence.consultation.mode || null,
      timeSpentSeconds: evidence.consultation.timeSpent || 0,
      stepsCompleted: evidence.consultation.stepsCompleted || 0,
      totalSteps: 7,
    },
    conversation: {
      totalMessages: evidence.conversation.totalMessages || 0,
      fiTones: evidence.conversation.fiTones || [],
    },
    progress: {
      totalPhases: 8,
      completedPhases: 8,
      completionRate: 1.0,
    },
    achievements: [
      "onboarding_pioneer",
      "philosophy_master",
      "hands_on_learner",
      "data_sovereign",
    ],
    metadata: {
      systemVersion: "0.1.0",
      architecture: "Local-first, HDF5, FastAPI + Next.js 16",
      philosophy: "Materia = Glitch, Humano = Beta, Residencia = Soberanía, Gnóstico = Tester",
    },
  };

  return JSON.stringify(data, null, 2);
}

/**
 * Generate HTML export (for PDF printing)
 */
export function generateHTMLExport(evidence: OnboardingEvidence): string {
  const html = `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AURITY Onboarding Report - ${evidence.sessionId}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      background: #f8fafc;
      padding: 2rem;
    }
    .container { max-width: 800px; margin: 0 auto; background: white; padding: 3rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    h1 { color: #0f172a; font-size: 2rem; margin-bottom: 0.5rem; border-bottom: 3px solid #10b981; padding-bottom: 0.5rem; }
    h2 { color: #334155; font-size: 1.5rem; margin-top: 2rem; margin-bottom: 1rem; border-left: 4px solid #06b6d4; padding-left: 1rem; }
    h3 { color: #475569; font-size: 1.25rem; margin-top: 1.5rem; margin-bottom: 0.75rem; }
    .meta { color: #64748b; font-size: 0.875rem; margin-bottom: 2rem; }
    .section { margin-bottom: 2rem; }
    ul { list-style: none; padding-left: 1.5rem; }
    li { margin-bottom: 0.5rem; padding-left: 1rem; position: relative; }
    li:before { content: "▸"; position: absolute; left: 0; color: #10b981; }
    .score { display: inline-block; background: #ecfdf5; color: #059669; padding: 0.25rem 0.75rem; border-radius: 0.375rem; font-weight: 600; margin-left: 0.5rem; }
    .badge { display: inline-block; background: #dbeafe; color: #1d4ed8; padding: 0.25rem 0.75rem; border-radius: 0.375rem; font-size: 0.875rem; margin: 0.25rem; }
    .footer { margin-top: 3rem; padding-top: 1.5rem; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 0.875rem; text-align: center; }
    .quote { font-style: italic; color: #475569; background: #f1f5f9; padding: 1rem; border-left: 3px solid #64748b; margin-top: 2rem; }
    code { background: #f1f5f9; padding: 0.125rem 0.375rem; border-radius: 0.25rem; font-family: 'Courier New', monospace; font-size: 0.875em; }
    @media print { body { padding: 0; } .container { box-shadow: none; } }
  </style>
</head>
<body>
  <div class="container">
    <h1>🏥 AURITY Onboarding Completion Report</h1>
    <div class="meta">
      <strong>Session ID:</strong> <code>${evidence.sessionId}</code><br>
      <strong>Completed At:</strong> ${new Date(evidence.completedAt).toLocaleString('es-MX', {
        timeZone: 'America/Mexico_City',
        dateStyle: 'full',
        timeStyle: 'long'
      })}
    </div>

    <div class="section">
      <h2>📋 User Profile</h2>
      <ul>
        <li><strong>Role:</strong> ${evidence.user.role || 'Not specified'}</li>
        <li><strong>Clinic Type:</strong> ${evidence.user.clinicType || 'Not specified'}</li>
        <li><strong>Consultas/day:</strong> ${evidence.user.consultasPerDay || 'Not specified'}</li>
        <li><strong>AI Experience:</strong> ${evidence.user.aiExperience || 'Not specified'}</li>
      </ul>
    </div>

    <div class="section">
      <h2>🧠 Philosophy Quiz Results</h2>

      <h3>Glitch Elegante (Materia)</h3>
      <p>Score: <span class="score">${evidence.philosophy.glitchScore || 0}/100</span></p>
      <p>Concept: Error budgets, SLO 99.9%, tolerance for imperfection</p>

      <h3>Beta Permanente (Humano)</h3>
      <p>Score: <span class="score">${evidence.philosophy.betaScore || 0}/100</span></p>
      <p>Concept: Continuous iteration, micro-coaching, never stop learning</p>

      <h3>Residencia (Dios Full-Stack)</h3>
      <p>Score: <span class="score">${evidence.philosophy.residenciaScore || 0}/100</span></p>
      <p>Concept: Data sovereignty, local-first, append-only HDF5</p>
    </div>

    <div class="section">
      <h2>👤 Patient Demo Data</h2>
      <ul>
        <li><strong>Nombre:</strong> ${evidence.patient.nombre || 'Not created'}</li>
        <li><strong>Edad:</strong> ${evidence.patient.edad ? `${evidence.patient.edad} años` : 'Not specified'}</li>
        <li><strong>Género:</strong> ${evidence.patient.genero || 'Not specified'}</li>
        ${evidence.patient.motivoConsulta ? `<li><strong>Motivo:</strong> ${evidence.patient.motivoConsulta}</li>` : ''}
      </ul>
    </div>

    <div class="section">
      <h2>🎬 Consultation Simulation</h2>
      <ul>
        <li><strong>Mode:</strong> ${evidence.consultation.mode ? evidence.consultation.mode.toUpperCase() : 'Not completed'}</li>
        <li><strong>Time Spent:</strong> ${evidence.consultation.timeSpent ? `${Math.round(evidence.consultation.timeSpent / 60)}m ${evidence.consultation.timeSpent % 60}s` : 'N/A'}</li>
        <li><strong>Steps Completed:</strong> ${evidence.consultation.stepsCompleted || 0}/7</li>
      </ul>
    </div>

    <div class="section">
      <h2>🏆 Achievements</h2>
      <div>
        <span class="badge">✅ Onboarding Pioneer</span>
        <span class="badge">✅ Philosophy Master</span>
        <span class="badge">✅ Hands-on Learner</span>
        <span class="badge">✅ Data Sovereign</span>
      </div>
    </div>

    <div class="quote">
      <em>"Materia = Glitch, Humano = Beta, Residencia = Soberanía, Gnóstico = Tester."</em><br>
      — Free-Intelligence
    </div>

    <div class="footer">
      Generated by Free-Intelligence AURITY System · Version 0.1.0<br>
      Architecture: Local-first, HDF5, FastAPI + Next.js 16
    </div>
  </div>
</body>
</html>`;

  return html;
}

/**
 * Download file to browser
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
