import { useState, useEffect, useCallback } from 'react';

import type { Release, ReleasesData } from '../types';

export interface UseReleasesReturn {
  releases: Release[];
  latestRelease: Release | undefined;
  loading: boolean;
  error: string | null;
  retry: () => void;
}

/**
 * Fetches releases from the static `/releases.json` generated by CI/CD.
 * Skips fetching when running inside Tauri (desktop mode).
 */
export function useReleases(skipFetch: boolean): UseReleasesReturn {
  const [releases, setReleases] = useState<Release[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchReleases = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch('/releases.json');
      if (!response.ok) {
        throw new Error(`Error al obtener releases: ${response.status}`);
      }

      const data: ReleasesData = await response.json();

      if (data.releases && data.releases.length > 0) {
        setReleases(data.releases);
      } else {
        setError('No hay releases disponibles');
      }
    } catch (err) {
      console.error('Error fetching releases:', err);
      setError('Error al cargar releases. Por favor intenta más tarde.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!skipFetch) {
      fetchReleases();
    } else {
      setLoading(false);
    }
  }, [skipFetch, fetchReleases]);

  return {
    releases,
    latestRelease: releases[0],
    loading,
    error,
    retry: fetchReleases,
  };
}
