// Aurity Desktop - License Validation Module
//
// This module handles:
// 1. License key decoding (AURITY-XXXX-XXXX-... format)
// 2. Ed25519 signature verification
// 3. License payload extraction (Auth0 config, features, expiration)
// 4. License storage in ~/.aurity/storage/license.json
//
// Security:
// - Public key embedded at compile time (from Python generator)
// - Signatures verified using ed25519-dalek
// - License data stored encrypted (future: with machine-bound KEK)

use chrono::{DateTime, Utc};
use data_encoding::BASE32_NOPAD;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

/// Embedded public key for license verification (base64-encoded PEM)
/// Generated by: fi license export-pubkey --format=base64
///
/// IMPORTANT: Replace this with your actual public key from:
/// ~/.aurity-admin/license.pub (base64 encoded)
const LICENSE_PUBLIC_KEY_B64: &str = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQXlkN2JIMTBCL21PMnhPYTNXVEFxUldET0RHZUMvRzNKL0tVVHA0TkJpUWs9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=";

/// License key prefix
const LICENSE_PREFIX: &str = "AURITY";

/// License payload structure (matches Python generator)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicensePayload {
    pub license_id: String,
    pub auth0_domain: String,
    pub auth0_client_id: String,
    pub auth0_audience: String,
    pub clinic_id: String,
    pub clinic_name: String,
    pub features: Vec<String>,
    pub issued_at: String,
    pub expires_at: String,
    pub version: String,
}

impl LicensePayload {
    /// Check if the license has expired
    pub fn is_expired(&self) -> bool {
        if self.expires_at.is_empty() {
            return false; // Perpetual license
        }

        match DateTime::parse_from_rfc3339(&self.expires_at) {
            Ok(expires) => Utc::now() > expires,
            Err(_) => {
                // Try ISO 8601 format with timezone
                if let Ok(expires) = DateTime::parse_from_str(&self.expires_at, "%Y-%m-%dT%H:%M:%S%.f%:z") {
                    Utc::now() > expires
                } else {
                    true // Invalid date = expired
                }
            }
        }
    }

    /// Days remaining until expiration (negative if expired)
    pub fn days_remaining(&self) -> Option<i64> {
        if self.expires_at.is_empty() {
            return None; // Perpetual license
        }

        let expires = DateTime::parse_from_rfc3339(&self.expires_at)
            .or_else(|_| DateTime::parse_from_str(&self.expires_at, "%Y-%m-%dT%H:%M:%S%.f%:z"))
            .ok()?;

        let duration = expires.signed_duration_since(Utc::now());
        Some(duration.num_days())
    }

    /// Check if a feature is enabled
    pub fn has_feature(&self, feature: &str) -> bool {
        self.features.iter().any(|f| f == feature)
    }
}

/// License validation status
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum LicenseStatus {
    Valid,
    Expired,
    InvalidSignature,
    InvalidFormat,
    NotActivated,
}

impl LicenseStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            LicenseStatus::Valid => "valid",
            LicenseStatus::Expired => "expired",
            LicenseStatus::InvalidSignature => "invalid_signature",
            LicenseStatus::InvalidFormat => "invalid_format",
            LicenseStatus::NotActivated => "not_activated",
        }
    }
}

/// Result of license validation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicenseValidationResult {
    pub status: String,
    pub is_valid: bool,
    pub message: String,
    pub days_remaining: Option<i64>,
    pub payload: Option<LicensePayload>,
}

/// Auth0 configuration extracted from license
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Auth0Config {
    pub domain: String,
    pub client_id: String,
    pub audience: String,
}

/// Stored license data (saved to disk)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredLicense {
    pub license_key: String,
    pub activated_at: String,
    pub payload: LicensePayload,
}

/// Get the license storage path
fn get_license_path() -> Result<PathBuf, String> {
    let home = dirs::home_dir()
        .ok_or_else(|| "Could not find home directory".to_string())?;
    Ok(home.join(".aurity").join("storage").join("license.json"))
}

/// Load the embedded public key
fn load_public_key() -> Result<VerifyingKey, String> {
    use base64::Engine;

    // Decode base64 to get PEM
    let pem_bytes = base64::engine::general_purpose::STANDARD
        .decode(LICENSE_PUBLIC_KEY_B64)
        .map_err(|e| format!("Failed to decode public key base64: {}", e))?;

    let pem_str = String::from_utf8(pem_bytes)
        .map_err(|e| format!("Invalid PEM encoding: {}", e))?;

    // Parse PEM to get raw key bytes
    // PEM format: -----BEGIN PUBLIC KEY-----\nBase64Data\n-----END PUBLIC KEY-----
    let lines: Vec<&str> = pem_str.lines().collect();
    let key_data: String = lines
        .iter()
        .filter(|line| !line.starts_with("-----"))
        .copied()
        .collect();

    let der_bytes = base64::engine::general_purpose::STANDARD
        .decode(&key_data)
        .map_err(|e| format!("Failed to decode PEM content: {}", e))?;

    // DER format for Ed25519 public key:
    // 30 2A (SEQUENCE, 42 bytes)
    //   30 05 (SEQUENCE, 5 bytes) - Algorithm identifier
    //     06 03 2B 65 70 (OID 1.3.101.112 = Ed25519)
    //   03 21 00 (BIT STRING, 33 bytes, 0 unused bits)
    //     [32 bytes of public key]

    if der_bytes.len() < 44 {
        return Err("Invalid DER encoding: too short".to_string());
    }

    // Extract the 32-byte public key from the end
    let key_bytes = &der_bytes[der_bytes.len() - 32..];

    VerifyingKey::from_bytes(key_bytes.try_into().map_err(|_| "Invalid key length")?)
        .map_err(|e| format!("Invalid Ed25519 public key: {}", e))
}

/// Decoded license data (payload, original payload bytes, signature bytes)
pub struct DecodedLicense {
    pub payload: LicensePayload,
    pub payload_bytes: Vec<u8>,  // Original bytes for signature verification
    pub signature_bytes: Vec<u8>,
}

/// Decode a license key into payload, original bytes, and signature
pub fn decode_license_key(license_key: &str) -> Result<DecodedLicense, String> {
    // Remove dashes and prefix
    let key = license_key.to_uppercase().replace('-', "");

    if !key.starts_with(LICENSE_PREFIX) {
        return Err(format!("Invalid license key: must start with {}", LICENSE_PREFIX));
    }

    let encoded = &key[LICENSE_PREFIX.len()..];

    // Decode base32
    let combined = BASE32_NOPAD
        .decode(encoded.as_bytes())
        .map_err(|e| format!("Invalid license key encoding: {}", e))?;

    // Extract payload length (first 4 bytes, big-endian)
    if combined.len() < 4 {
        return Err("Invalid license key: too short".to_string());
    }

    let payload_len = u32::from_be_bytes([combined[0], combined[1], combined[2], combined[3]]) as usize;

    // Extract payload and signature
    if combined.len() < 4 + payload_len + 64 {
        return Err("Invalid license key: incomplete data".to_string());
    }

    let payload_bytes = combined[4..4 + payload_len].to_vec();
    let signature_bytes = combined[4 + payload_len..4 + payload_len + 64].to_vec();

    // Parse payload JSON
    let payload_str = String::from_utf8(payload_bytes.clone())
        .map_err(|e| format!("Invalid payload encoding: {}", e))?;

    let payload: LicensePayload = serde_json::from_str(&payload_str)
        .map_err(|e| format!("Invalid license payload: {}", e))?;

    Ok(DecodedLicense {
        payload,
        payload_bytes,
        signature_bytes,
    })
}

/// Verify a license key's signature
pub fn verify_license_signature(license_key: &str) -> Result<LicensePayload, String> {
    let decoded = decode_license_key(license_key)?;

    // Load public key
    let public_key = load_public_key()?;

    // Create signature from bytes (ed25519-dalek 2.x: from_bytes takes &[u8; 64] and returns Signature directly)
    let sig_array: [u8; 64] = decoded.signature_bytes
        .as_slice()
        .try_into()
        .map_err(|_| "Invalid signature length: expected 64 bytes")?;
    let signature = Signature::from_bytes(&sig_array);

    // Verify using the ORIGINAL payload bytes (not re-serialized)
    // This ensures we verify exactly what was signed, avoiding JSON serialization differences
    public_key
        .verify(&decoded.payload_bytes, &signature)
        .map_err(|_| "Invalid license signature".to_string())?;

    Ok(decoded.payload)
}

/// Validate a license key completely
pub fn validate_license(license_key: &str) -> LicenseValidationResult {
    // Step 1: Verify signature
    let payload = match verify_license_signature(license_key) {
        Ok(p) => p,
        Err(e) => {
            let status = if e.contains("encoding") || e.contains("format") {
                LicenseStatus::InvalidFormat
            } else {
                LicenseStatus::InvalidSignature
            };
            return LicenseValidationResult {
                status: status.as_str().to_string(),
                is_valid: false,
                message: e,
                days_remaining: None,
                payload: None,
            };
        }
    };

    // Step 2: Check expiration
    if payload.is_expired() {
        return LicenseValidationResult {
            status: LicenseStatus::Expired.as_str().to_string(),
            is_valid: false,
            message: "License has expired".to_string(),
            days_remaining: payload.days_remaining(),
            payload: Some(payload),
        };
    }

    // License is valid!
    LicenseValidationResult {
        status: LicenseStatus::Valid.as_str().to_string(),
        is_valid: true,
        message: "License is valid".to_string(),
        days_remaining: payload.days_remaining(),
        payload: Some(payload),
    }
}

/// Activate a license key (store to disk)
pub fn activate_license(license_key: &str) -> Result<LicensePayload, String> {
    // First validate the license
    let result = validate_license(license_key);

    if !result.is_valid {
        return Err(result.message);
    }

    let payload = result.payload.ok_or("No payload in valid license")?;

    // Create storage directory
    let license_path = get_license_path()?;
    if let Some(parent) = license_path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Failed to create storage directory: {}", e))?;
    }

    // Store license
    let stored = StoredLicense {
        license_key: license_key.to_string(),
        activated_at: Utc::now().to_rfc3339(),
        payload: payload.clone(),
    };

    let json = serde_json::to_string_pretty(&stored)
        .map_err(|e| format!("Failed to serialize license: {}", e))?;

    fs::write(&license_path, json)
        .map_err(|e| format!("Failed to write license file: {}", e))?;

    println!("[Aurity] License activated: {}", payload.license_id);

    Ok(payload)
}

/// Get stored license status
pub fn get_license_status() -> LicenseValidationResult {
    let license_path = match get_license_path() {
        Ok(p) => p,
        Err(e) => {
            return LicenseValidationResult {
                status: LicenseStatus::InvalidFormat.as_str().to_string(),
                is_valid: false,
                message: e,
                days_remaining: None,
                payload: None,
            };
        }
    };

    if !license_path.exists() {
        return LicenseValidationResult {
            status: LicenseStatus::NotActivated.as_str().to_string(),
            is_valid: false,
            message: "No license activated".to_string(),
            days_remaining: None,
            payload: None,
        };
    }

    // Read stored license
    let content = match fs::read_to_string(&license_path) {
        Ok(c) => c,
        Err(e) => {
            return LicenseValidationResult {
                status: LicenseStatus::InvalidFormat.as_str().to_string(),
                is_valid: false,
                message: format!("Failed to read license file: {}", e),
                days_remaining: None,
                payload: None,
            };
        }
    };

    let stored: StoredLicense = match serde_json::from_str(&content) {
        Ok(s) => s,
        Err(e) => {
            return LicenseValidationResult {
                status: LicenseStatus::InvalidFormat.as_str().to_string(),
                is_valid: false,
                message: format!("Invalid license file format: {}", e),
                days_remaining: None,
                payload: None,
            };
        }
    };

    // Re-validate the stored license key (checks signature + expiration)
    validate_license(&stored.license_key)
}

/// Get Auth0 configuration from stored license
pub fn get_auth0_config() -> Result<Auth0Config, String> {
    let status = get_license_status();

    if !status.is_valid {
        return Err(status.message);
    }

    let payload = status.payload.ok_or("No payload in valid license")?;

    Ok(Auth0Config {
        domain: payload.auth0_domain,
        client_id: payload.auth0_client_id,
        audience: payload.auth0_audience,
    })
}

/// Clear stored license (for testing/logout)
pub fn clear_license() -> Result<(), String> {
    let license_path = get_license_path()?;

    if license_path.exists() {
        fs::remove_file(&license_path)
            .map_err(|e| format!("Failed to remove license file: {}", e))?;
    }

    Ok(())
}

// ============================================================================
// Tauri Commands
// ============================================================================

/// Validate a license key (Tauri command)
#[tauri::command]
pub fn validate_license_key(key: String) -> LicenseValidationResult {
    validate_license(&key)
}

/// Activate a license key (Tauri command)
#[tauri::command]
pub fn activate_license_key(key: String) -> Result<LicensePayload, String> {
    activate_license(&key)
}

/// Get current license status (Tauri command)
#[tauri::command]
pub fn get_current_license_status() -> LicenseValidationResult {
    get_license_status()
}

/// Get Auth0 config from license (Tauri command)
#[tauri::command]
pub fn get_license_auth0_config() -> Result<Auth0Config, String> {
    get_auth0_config()
}

/// Check if a feature is enabled (Tauri command)
#[tauri::command]
pub fn check_feature_enabled(feature: String) -> bool {
    let status = get_license_status();
    status.payload
        .map(|p| p.has_feature(&feature))
        .unwrap_or(false)
}

/// Clear license (Tauri command)
#[tauri::command]
pub fn clear_stored_license() -> Result<(), String> {
    clear_license()
}

// ============================================================================
// Online Renewal API Client
// ============================================================================

/// Renewal API base URL (production)
const RENEWAL_API_BASE: &str = "https://app.aurity.io/api";

/// Renewal request sent to server
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RenewalRequest {
    pub license_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub machine_fingerprint: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub current_expires_at: Option<String>,
}

/// Renewal response from server
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RenewalResponse {
    pub renewed: bool,
    pub reason: Option<String>,
    pub new_expires_at: Option<String>,
    pub new_license_key: Option<String>,
    pub renewal_url: Option<String>,
    pub message: String,
}

/// License renewal status for frontend
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RenewalStatus {
    pub needs_renewal: bool,
    pub days_until_expiry: Option<i64>,
    pub renewal_url: Option<String>,
    pub warning_message: Option<String>,
}

/// Get machine fingerprint for license binding (simplified)
fn get_machine_fingerprint() -> Option<String> {
    // Simple fingerprint: combine hostname + OS
    let hostname = hostname::get().ok()?.into_string().ok()?;

    #[cfg(target_os = "macos")]
    let os_id = "macos";
    #[cfg(target_os = "windows")]
    let os_id = "windows";
    #[cfg(target_os = "linux")]
    let os_id = "linux";
    #[cfg(not(any(target_os = "macos", target_os = "windows", target_os = "linux")))]
    let os_id = "unknown";

    // Create a simple fingerprint hash
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let mut hasher = DefaultHasher::new();
    format!("{}-{}", hostname, os_id).hash(&mut hasher);
    Some(format!("{:016x}", hasher.finish()))
}

/// Check if license needs renewal (called periodically)
pub fn check_renewal_status() -> RenewalStatus {
    let status = get_license_status();

    if !status.is_valid && status.status != "expired" {
        return RenewalStatus {
            needs_renewal: false,
            days_until_expiry: None,
            renewal_url: None,
            warning_message: Some("License not activated".to_string()),
        };
    }

    let days = status.days_remaining.unwrap_or(0);

    // Warning thresholds
    let warning_message = if days < 0 {
        Some("Your license has expired. Please renew to continue using Aurity.".to_string())
    } else if days <= 7 {
        Some(format!("Your license expires in {} days. Please renew soon.", days))
    } else if days <= 30 {
        Some(format!("Your license expires in {} days.", days))
    } else {
        None
    };

    let license_id = status.payload
        .as_ref()
        .map(|p| p.license_id.clone())
        .unwrap_or_default();

    RenewalStatus {
        needs_renewal: days <= 30,
        days_until_expiry: status.days_remaining,
        renewal_url: if days <= 30 {
            Some(format!("https://app.aurity.io/renew?license={}", license_id))
        } else {
            None
        },
        warning_message,
    }
}

/// Request license renewal from server (async HTTP call)
pub async fn request_renewal() -> Result<RenewalResponse, String> {
    let status = get_license_status();

    let payload = status.payload.ok_or("No valid license to renew")?;

    let request = RenewalRequest {
        license_id: payload.license_id.clone(),
        machine_fingerprint: get_machine_fingerprint(),
        current_expires_at: Some(payload.expires_at.clone()),
    };

    // Make HTTP request to renewal API
    let client = reqwest::Client::new();
    let response = client
        .post(format!("{}/licenses/renew", RENEWAL_API_BASE))
        .json(&request)
        .timeout(std::time::Duration::from_secs(30))
        .send()
        .await
        .map_err(|e| format!("Network error: {}", e))?;

    if !response.status().is_success() {
        let status = response.status();
        let body = response.text().await.unwrap_or_default();
        return Err(format!("Server error {}: {}", status, body));
    }

    let renewal: RenewalResponse = response
        .json()
        .await
        .map_err(|e| format!("Invalid response: {}", e))?;

    // If renewal succeeded and we got a new license key, activate it
    if renewal.renewed {
        if let Some(ref new_key) = renewal.new_license_key {
            activate_license(new_key)?;
            println!("[Aurity] License renewed successfully!");
        }
    }

    Ok(renewal)
}

/// Register license for renewal service
pub async fn register_for_renewal(license_key: &str) -> Result<(), String> {
    let client = reqwest::Client::new();

    let response = client
        .post(format!("{}/licenses/register", RENEWAL_API_BASE))
        .query(&[("license_key", license_key)])
        .timeout(std::time::Duration::from_secs(30))
        .send()
        .await
        .map_err(|e| format!("Network error: {}", e))?;

    if !response.status().is_success() {
        let status = response.status();
        let body = response.text().await.unwrap_or_default();
        return Err(format!("Registration failed {}: {}", status, body));
    }

    println!("[Aurity] License registered for renewal service");
    Ok(())
}

// ============================================================================
// Renewal Tauri Commands
// ============================================================================

/// Check if license needs renewal (Tauri command)
#[tauri::command]
pub fn check_license_renewal_status() -> RenewalStatus {
    check_renewal_status()
}

/// Request license renewal from server (Tauri command - async)
#[tauri::command]
pub async fn request_license_renewal() -> Result<RenewalResponse, String> {
    request_renewal().await
}

/// Register license for renewal tracking (Tauri command - async)
#[tauri::command]
pub async fn register_license_for_renewal(license_key: String) -> Result<(), String> {
    register_for_renewal(&license_key).await
}
